SET CURRENT SQLID = 'CCFP01'

---NELL'OGGETTO DEL BOLLETTINO SCRIVERE OK SE NON CI PROBLEMI, DIVERSAMENTE KO SE C'è QUALCOSA CHE NON è ANDATO BENE DELLE QUERY SOTTO.
---SCRIVERE OK ANCHE IN CASO CI SIANO SCARTI CONTABILI

--Start Giornaliera
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CCGPSP01%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--End giornaliera
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CCGPSPX2%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--CONTROLLARE CHE CI SIANO SU TSFOGLIO ST03, FT01, KP05

--Flusso CCGPCG7B
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('CCGPCG7B')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC


--Flussi antiricl
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('CCGPAR81','CCGPARS1','CCSPAR53')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC

select P.NUM_ID, P.COD_PROC, c.des_proc, P.COD_OUTP, P.FLG_STAT, P.DES_FILE,c.des_outp, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS
from scpr_logproc p
,tcon_dlvqueue d
,SCPR_OUTPUT_NEW c
where p.cod_proc in ('CCGPIF82','CCGPIF87','CCGPIF86','CCGPIF89')
and d.num_id = p.num_id
AND DATE(TMS_SEND) = '2024-06-01'
and p.COD_PROC = c.COD_PROC
AND p.COD_OUTP = c.COD_OUTP
AND P.COD_SOCRIFERIMENTO = C.COD_SOCRIFERIMENTO
order by p.tms_cens desc


--FLUSSI GBC MENSILI (SOLO POST MENSILE)
select  P.NUM_ID, P.COD_PROC, c.des_proc, P.COD_OUTP, P.FLG_STAT, P.DES_FILE,c.des_outp, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS
from scpr_logproc p
    ,tcon_dlvqueue d
    ,SCPR_OUTPUT_NEW c
where p.cod_proc in ('CCMPIF82','CCMPIF86','CCMPIF87','CCMPIF89','CCMPIF84','CCMPIF85')
and d.num_id = p.num_id
AND DATE(TMS_SEND) = '2022-00-01'
and p.COD_PROC = c.COD_PROC
AND p.COD_OUTP = c.COD_OUTP
order by  p.tms_cens desc

--ESITO CONSERVAZIONE SOSTITUTIVA -> RARAMENTE ESTRAE QUALCOSA, SE NON ESTRAE NULLA OK, SE ESTRAE RECORD IN STATO 2 LASCIARLI LI (RIENTRERANNO IN AUTOMATICO).
SELECT ID_PAPIRO,COD_STAT,
    CASE(COD_STAT)
      WHEN '0' THEN 'Stato 0: record da elaborare'
      WHEN '1' THEN 'Stato 1: record in elaborazione'
      WHEN '2' THEN 'Stato 2: record elaborato, attesa esito'
      WHEN '3' THEN 'Stato 3: record in errore'
      END as DESCRIZIONE_STATO,
    CASE(COD_STAT)
      WHEN '3' THEN DES_ESITO
      END as ERRORE,
    CASE(COD_STAT)
        WHEN '0' THEN TMS_VARZ
        WHEN '1' THEN TMS_VARZ
        END as TMS_INVIO
FROM TDOC_CPFILEXT where COD_STAT <> '4' ;

--VERIFICA FATTURE IN ERRORE, IGNORARE QUELLE VECCHIE DEL 2019.
SELECT * FROM FOPT_FATELXML
WHERE COD_STAT_INVI <> '002'

--SCARTI CONTABILI
SELECT * FROM FCGT_MOVIECBC
WHERE COD_STAT_MOVI = 'S'
AND COD_SOCRIFERIMENTO = '15'

--VERIFICA GENERICA DI CIò CHE è ANDATO IN ERRORE
SELECT * FROM SCPR_ELABTIME
WHERE DES_ESITO LIKE '%ERROR%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--VERIFICA GENERICA DI OUTPUT ANDATI IN ERRORE
select * from scpr_logproc 
where (flg_stat in ('3') or (flg_stat ='1' and cod_outp<>'WEB'))   
and date(tms_cens) >= '2023-06-01'
order by num_id desc

--Remote Factoring
select * from CCFP01.FRFT_TRACCERF
where cod_socriferimento = '15'
and cod_rife not in ('DWX011', 'DWX070', 'DWX027', 'BANCSOGG', 'DETMOVCO', 'MOVPARTI', 'SCADENRF', 'INTRPRTT')
and COD_RIFE in ('AFFIDCED','ANAGRAFE','CONTICOR','FIDICOPP')

--CONSOLE MANAGEMENT
SELECT * FROM SCPR_ELABTIME
where (COD_PROC like '%DW11%' or COD_PROC like '%DW17%'or COD_PROC like '%DW27%')
order by DAT_ELAB desc , tim_start desc

--INVIARE LE PEC DA JOD->CONTROLLO OUTPUT->INVIO MAIL PEC->LANCIARE IL JOB ---- CON QUESTA QUERY SI VERIFICA CHE SIA PARTITO IL JOB
select * from scpr_elabtime
where cod_proc like '%TC01%'
order by dat_elab desc
