SET CURRENT SQLID = 'CFFP01'

--  :DATACONTABILE  = sostituire con data contabile

SELECT * FROM K4F_SERVIZIO

--Data inizio giornaliera: gg/mm/aaaa H: hh:mm:gg
--Da recuperare con la seguente query
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CFGPSP01%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--Data fine giornaliera:    gg/mm/aaaa H: hh:mm:gg
--Da recuperare con la seguente query
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CFGPSP02%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--Data inizio settimanale: gg/mm/aaaa H: hh:mm:gg
--Da recuperare con la seguente query SOLO IL LUNEDì
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CFSPSP01%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--Data fine settimanale:    gg/mm/aaaa H: hh:mm:gg
--Da recuperare con la seguente query SOLO IL LUNEDì
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CFSPSP02%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--Data inizio decadale: gg/mm/aaaa H: hh:mm:gg
--Da recuperare con la seguente query
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CFDPSP01%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--Data fine decadale:    gg/mm/aaaa H: hh:mm:gg
--Da recuperare con la seguente query
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CFDPSP02%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--Data inizio mensile: gg/mm/aaaa H: hh:mm:gg
--Da recuperare con la seguente query
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CFMPSP01%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--Data fine mensile: gg/mm/aaaa H: hh:mm:gg
--Da recuperare con la seguente query
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%CFMPSP02%'
ORDER BY DAT_ELAB DESC, TIM_START DESC


-- job in errore invece che mail
SELECT * FROM SCPR_ELABTIME
WHERE DES_ESITO = 'ERROR'
ORDER BY DAT_ELAB DESC, TIM_START DESC;


-- controllo invio flussi  ( SEPA, COGE … )  
SELECT * FROM TCON_DLVQUEUE
WHERE DLV_STATUS <> '02'
AND DATE(TMS_CENS) >=  :DATACONTABILE
ORDER BY TMS_CENS DESC


-- controllo post-office
SELECT * from SCPR_LOGPROC
where COD_PROC = 'MULTIDLV'
order by TMS_CENS desc ;


--Controllo output TSfoglio
select * from scpr_logproc 
where (flg_stat in ('3') or (flg_stat ='1' and cod_outp<>'WEB'))   
and date(tms_cens) >= :DATACONTABILE
---and  COD_PROC <> 'CFRPPF70' AND COD_OUTP <> 'FTABUL'
---and  COD_PROC <> 'CFGPSF18' AND COD_OUTP <> 'FCESSXML' 
---and  COD_PROC <> 'CFGPQYBL' AND COD_OUTP <> 'AO02'
---and  COD_PROC <> 'CFGPQY70' AND COD_OUTP <> 'IL07' -- vigilanza
---and COD_PROC  <> 'CFMPDB31' AND COD_OUTP <> 'XLSDB31 '
order by num_id desc;


----- PRODUZIONE OUTPUT (TSfoglio)  

--CFGPST33 – Lettera notifiche
SELECT * FROM SCPR_LOGPROC 
WHERE  COD_PROC =  'CFGPST33' 
AND COD_OUTP='FNOTIF'  
AND DATE(TMS_CENS) = :DATACONTABILE
ORDER BY NUM_ID DESC;	

Poi aprire pdf in Tsfoglio e verificare coerenza data documento con data elaborazione

--CFGPFT01 – Fatture
SELECT * FROM SCPR_LOGPROC 
WHERE  COD_PROC =  'CFGPFT01' 
AND COD_OUTP='DOCXML'  
AND DATE(TMS_CENS) =  :DATACONTABILE
ORDER BY NUM_ID DESC;

--CFGPLQ01 – Contabili di bonifico e storno
SELECT *
FROM SCPR_LOGPROC P
WHERE P.COD_PROC = 'CFGPLQ01'
AND COD_OUTP = 'XMLSTP' 
ORDER BY P.TMS_CENS DESC, P.COD_OUTP;

-- FLUSSI SETTIMANALI ---> PER ORA DA NON SEGNALARE
--CFSPST30 –  Solleciti di pagamento
SELECT * FROM SCPR_LOGPROC 
WHERE  COD_PROC =  'CFSPST30' 
AND COD_OUTP = 'FISOLXML'  
ORDER BY TMS_CENS DESC;


--CONTROLLI MENSILI TSFOGLIO

--- FATTURE COMPETENZE MENSILI
SELECT * FROM SCPR_LOGPROC 
WHERE  COD_PROC =  'CFMPFT01'
AND COD_OUTP='DOCXML'  
AND DATE(TMS_CENS) >=  :DATACONTABILE
ORDER BY NUM_ID DESC;

--- FATTURE STAFFA CEDENTE
SELECT * FROM SCPR_LOGPROC 
WHERE  COD_PROC =  'CFMPFT67'
AND COD_OUTP='DOCXML'  
AND DATE(TMS_CENS) >=  :DATACONTABILE
ORDER BY NUM_ID DESC;

--- FATTURE STAFFA DEBITORE
SELECT * FROM SCPR_LOGPROC 
WHERE  COD_PROC =  'CFMPFT91'
AND COD_OUTP='DOCXML'  
AND DATE(TMS_CENS) >=  :DATACONTABILE
ORDER BY NUM_ID DESC;

--- FATTURE PER INTERESSI DI PLUS FACTORING
SELECT * FROM SCPR_LOGPROC 
WHERE  COD_PROC =  'CFMPFT43'
AND COD_OUTP='DOCXML'  
AND DATE(TMS_CENS) >=  :DATACONTABILE
ORDER BY NUM_ID DESC;

--- ESTRATTI CONTO
SELECT * FROM SCPR_LOGPROC 
WHERE  COD_PROC  IN (  'CFMPST32' , 'CFMPST23', 'CFMPST27')
AND COD_OUTP = 'FESCOXML'
AND DATE(TMS_CENS) >=  :DATACONTABILE
ORDER BY NUM_ID DESC;


-----FLUSSI GIORNALIERI VS BANCA

--FLUSSO COGE 
--CFGPCG90 –  Flusso contabile CF+
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('CFGPCG90')
and COD_OUTP = 'CSVXF'
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC ;

--FLUSSI ABACO
--CFGPKR23 –  Finanziamenti – KRP123O1
--CFGPKR23 –  Ammortamenti - KRP123O2
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('CFGPKRC3')
and COD_OUTP in ('KRP123O2','KRP123O1')
AND P.NUM_ID = D.NUM_ID
AND D.COD_IDELIVERY in ('SFTP_G_GFIA','SFTP_G_GFIF')
ORDER BY P.TMS_CENS DESC ;


--FLUSSO DOD
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('CFGPFDD4')
and COD_OUTP in ('FLUSCESS')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC;


-- FLUSSI GIORNALIERI DWH -- CONTROLLARE CHE SIANO 18
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE ( (P.COD_PROC='CFGPW225' AND P.COD_OUTP='FCSVRATI')
OR (P.COD_PROC='CFGPW222' AND P.COD_OUTP='FCSVCR  ')
OR (P.COD_PROC='CFGPW221' AND P.COD_OUTP='FCSVPEF ')
OR (P.COD_PROC='CFGPW220' AND P.COD_OUTP='FCSVPRIC')
OR (P.COD_PROC='CFGPW219' AND P.COD_OUTP='FCSVFATT')
OR (P.COD_PROC='CFGPW214' AND P.COD_OUTP='FCSVPART')
OR (P.COD_PROC='CFGPW212' AND P.COD_OUTP='FCSVRIAS')
OR (P.COD_PROC='CFGPW211' AND P.COD_OUTP='FCSVEROG')
OR (P.COD_PROC='CFGPW210' AND P.COD_OUTP='FCSVGARA')
OR (P.COD_PROC='CFGPW209' AND P.COD_OUTP='FCSVFDSO')
OR (P.COD_PROC='CFGPW208' AND P.COD_OUTP='FCSVSCAD')
OR (P.COD_PROC='CFGPW207' AND P.COD_OUTP='FCSVCESS')
OR (P.COD_PROC='CFGPW206' AND P.COD_OUTP='FCSVCRED')
OR (P.COD_PROC='CFGPW205' AND P.COD_OUTP='FCSVINCA')
OR (P.COD_PROC='CFGPW204' AND P.COD_OUTP='FCSVCONT')
OR (P.COD_PROC='CFGPW203' AND P.COD_OUTP='FCSVCOPP')
OR (P.COD_PROC='CFGPW202' AND P.COD_OUTP='FCSVFIDI')
OR (P.COD_PROC='CFGPW201' AND P.COD_OUTP='FCSVANAG') )
AND P.NUM_ID = D.NUM_ID
AND DATE(P.TMS_CENS) >= :DATACONTABILE
AND D.COD_DELIVERY = 'SFTP'
ORDER BY P.TMS_CENS DESC, P.COD_PROC DESC ;

-----FLUSSI GIORNALIERI DA BANCA

-- FLUSSO GUIDA ABACO
SELECT * FROM SCPR_ELABTIME
where COD_PROC = 'CFGPKRC4'
order by DAT_ELAB desc , tim_start desc;

-- FLUSSO RH
SELECT * FROM SCPR_ELABTIME
where COD_PROC = 'CFGPIS65'
order by DAT_ELAB desc , tim_start desc;

--verifica interna - se ci sono occorrenze OK
SELECT * FROM FOPT_DOCUMENT
WHERE COD_SOCRIFERIMENTO = '36'
AND COD_TIPO_DOCU='D14'
AND COD_STIP_DOCU='ELE'
and COD_USERID='ISP065  '
and DAT_REGI = DATA_CONTABILE
order by tms_cens desc


-----FLUSSI DECADALI -- NON ANCORA ATTIVO

--FLUSSO AUI 
--CFGPARF1 –  Movimenti  Flusso
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('CFDPARF1')
and COD_OUTP in ('RAPPMOVI')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC ;


------ FLUSSI MENSILI
-- FLUSSO COGE
-- CFMPCG90 –  Flusso contabile - Nome file prodotto: SIBCONT 
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('CFMPCG90')
and COD_OUTP in ('CSVXF')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC;

-- FLUSSI MENSILI DWH
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE (  (P.COD_PROC='CFMPW225' AND P.COD_OUTP='FCSVRATI')
OR (P.COD_PROC='CFMPW222' AND P.COD_OUTP='FCSVCR  ')
OR (P.COD_PROC='CFMPW221' AND P.COD_OUTP='FCSVPEF ')
OR (P.COD_PROC='CFMPW220' AND P.COD_OUTP='FCSVPRIC')
OR (P.COD_PROC='CFMPW219' AND P.COD_OUTP='FCSVFATT')
OR (P.COD_PROC='CFMPW214' AND P.COD_OUTP='FCSVPART')
OR (P.COD_PROC='CFMPW212' AND P.COD_OUTP='FCSVRIAS')
OR (P.COD_PROC='CFMPW211' AND P.COD_OUTP='FCSVEROG')
OR (P.COD_PROC='CFMPW210' AND P.COD_OUTP='FCSVGARA')
OR (P.COD_PROC='CFMPW209' AND P.COD_OUTP='FCSVFDSO')
OR (P.COD_PROC='CFMPW208' AND P.COD_OUTP='FCSVSCAD')
OR (P.COD_PROC='CFMPW207' AND P.COD_OUTP='FCSVCESS')
OR (P.COD_PROC='CFMPW206' AND P.COD_OUTP='FCSVCRED')
OR (P.COD_PROC='CFMPW205' AND P.COD_OUTP='FCSVINCA')
OR (P.COD_PROC='CFMPW204' AND P.COD_OUTP='FCSVCONT')
OR (P.COD_PROC='CFMPW203' AND P.COD_OUTP='FCSVCOPP')
OR (P.COD_PROC='CFMPW202' AND P.COD_OUTP='FCSVFIDI')
OR (P.COD_PROC='CFMPW201' AND P.COD_OUTP='FCSVANAG')  )
AND P.NUM_ID = D.NUM_ID
AND DATE(P.TMS_CENS) >=  :DATACONTABILE
AND D.COD_DELIVERY = 'SFTP'
ORDER BY P.TMS_CENS DESC, P.COD_PROC DESC ;

--BLMUEXIL - Compliance - Controlli secondo livello - Nome file prodotto: REPCSV
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('BLMUEXIL')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC ;


-- SCARTI CONTABILI
SELECT * FROM FCGT_MOVIECBC
WHERE COD_STAT_MOVI = 'S'

-- REPORTING DIREZIONALE
SELECT * FROM SCPR_ELABTIME
where (COD_PROC like '%DW72%' or COD_PROC like '%DW70%')
order by DAT_ELAB desc , tim_start desc;

-- CONSOLE MANAGEMENT
SELECT * FROM SCPR_ELABTIME
where (COD_PROC like '%DW11%' or COD_PROC like '%DW17%'or COD_PROC like '%DW27%')
order by DAT_ELAB desc , tim_start desc;
