SET CURRENT SQLID ='CFFP01'

SELECT COD_STAT_SOGG, COD_LING_USER,DES_STAT_SOGG FROM GDET_CTLSTSOG

SELECT COD_TIPO_SOGG, DES_TIPO_SOGG FROM GDET_CTLTSOGG

SELECT COD_SPEC_GIUR,DES_SPEC_GIUR,FLG_RESI,COD_SPEC_GIUR_CRBI,COD_SPEC_GIUR_ANAG FROM GDET_CTLSPGIU

SELECT * FROM GDET_CTLMOtpa

SELECT IMP_FATT_DA, IMP_FATT_A , COD_TIPO_FATT, DES_TIPO_FATT FROM GDET_CTLTIFAT

SELECT COD_RISC, DES_RISC, COD_RISC_FAMI, COD_RISC_SEGN FROM GDET_CTLSTRIS

SELECT COD_PROC, DES_PROC FROM GDET_CTLSTPRO

SELECT COD_LINEA_SISTEMA, DES_RID_LINEA_SIST, DES_EST_LINEA_SIST, FLG_CLAS_CRED, FLG_GEST_MATU, FLG_ACCO_UTIL,FLG_UTO,FLG_NOT_NOTF,FLG_MATY,FLG_DILA,FLG_SOLO_GEST,DAT_INIZ,DAT_FINE,
FLG_SOLO_CESS FROM GDET_CTLLSIST

SELECT COD_CLAS_CRED, DES_CLAS_CRED FROM GDET_CTBCLCRE

SELECT  COD_STATO_LIN_PLAF, DES_STATO_LIN_PLAF FROM GDET_CTLSTALN

SELECT COD_MOTI_REVO, DES_MOTI_REVO, FLG_LIN_CRED,  
FLG_GARA,FLG_PLAF,FLG_POOL,FLG_COPP FROM GDET_CTLTREVO

SELECT 
COD_MERC, 
DES_MERC,FLG_DOME FROM GDET_CTLMERCA

SELECT COD_TIPO_CNCE, DES_TIPO_CNCE FROM GDET_CTLTCNCE

SELECT COD_TIPO_CONT, DES_TIPO_CONT FROM GDET_CTLTICON

SELECT COD_TIPO_CAPZ, DES_TIPO_CAPZ FROM GDET_CTLTCPTZ

SELECT
COD_TIPO_COPP, DES_TIPO_COPP FROM GDET_CTLTPCOP

SELECT 
COD_COND, DES_COND, 
COD_LIVE_COND, 
DES_AGGA_TRSP FROM FKNT_ANACONLI

SELECT COD_TIPO_VALO, 
DES_TIPO_VALO FROM GDET_CTLTVALO

SELECT * FROM GDET_CTLTCOND

SELECT COD_TIPO_PRTT,  DES_TIPO_PRTT, COD_SIGL_PRTT, COD_NATU_PRTT, COD_TIPO_PRTT_ORIG, COD_SEGN FROM GDET_CTLTIPAR

SELECT COD_STAT_PRTT, DES_STAT_PRTT FROM GDET_CTLSTPAR

SELECT COD_MEZZ_INCA, DES_MEZZ_INCA, QTA_GIOR_INCA, COD_LIVE_RISC FROM GDET_CTLMEZIN

SELECT COD_TIPO_FAMG_SOLL, DES_TIPO_FAMG_SOLL FROM GDET_CTLTFASO

SELECT COD_TIPO_RAGG, DES_TIPO_RAGG, COD_SUPT_RAGG, FLG_TIPO_CARI FROM GDET_CTLTIRAG

SELECT COD_VAL_PARAMETRO, DES_CODICE_PARAM FROM GDET_CTLVALOP

SELECT COD_CLSS_RISC, DES_CLSS_RISC_RIDT, DES_CLSS_RISC_ESTS, FLG_CLSS_RISC, FLG_TIPO_CLSS_RISC FROM GDET_CTLCLRIS

SELECT COD_MOTI_DECL, DES_MOTI_DECL, FLG_LIN_CRED, FLG_PLAF,FLG_COPP,FLG_DECL_LIN_CRED, FLG_REVO_LIN_CRED,FLG_RIAS FROM GDET_CTLTDECL


