SET CURRENT SQLID = 'CRFP01'
 
--ticket 2024/149

SELECT * FROM FFGT_LICREPAR
WHERE NUM_PR_LIN_CREDITO = 79747 --(linea di credito)
and cod_param_lin_sist in ( '280','180' )


-- IN  sintesi si vanno a mettere a N questi parametri 
-- si sospende ticket e quando hanno finito li rimettiamo a s
-- caso salvato nei doc 'CRD Sblocco conto NAQ'
--- Si sospende  E POI SI CHIUDE 


--ticket 2024/148


SELECT * FROM FFGT_IDOCUMEN
--SET   COD_SOCRIFERIMENTO = 'FM'
WHERE COD_SOGGETTO = 109042
AND   COD_DOCUMENTO = 'SDD'
AND   NUM_PR_DOCUMENTAZ = 157384



UPDATE  FFGT_IDOCUMEN
SET COD_SOCRIFERIMENTO = 'HD'
WHERE COD_SOGGETTO = 109042
AND   COD_DOCUMENTO = 'SDD'
AND   NUM_PR_DOCUMENTAZ = 157384


--creazione utenza pef credem 
--Estraggo l'utente appena creato su k4f e l'utente da copiare 
SELECT * FROM ISIT_UTENTI 
WHERE COD_UTEN IN ('T0R162              ','T0R164              ') --- T0R162 UTENZA CLONE 
--per estrarre il codice soggetto del profilo da copiare (vesco è il cognome della tizia) 
SELECT * FROM GAGT_NDG  
WHERE DES_SOGG_UTEN LIKE '%VAGO%' -- 107378 UTENZA CLONE 

SELECT * FROM GAGT_NDG  
WHERE COD_SOGGETTO IN ('107378','106828') --- 106828 UTENZA DA CENSIRE 

INSERT INTO GAGT_NDG (COD_SOGGETTO,DES_SOGG_UTEN,COD_SOCT_CENS,COD_TIPO_SOGG,DES_INDI_SELE,COD_CAP_SELE,DES_LOCA_SELE,COD_PROV_SELE,COD_NAZI_SELE,COD_CAB_SELE,DES_COMU_SELE,COD_ENTE_MODI,COD_ENTE_CENS,DAT_CENS,TIM_STAT,DES_ANAG_INDI_SELE,FLG_PEP,FLG_ANTI_TERR,FLG_SPLIT_PAYM,FLG_ESCL_MON_SCAD,FLG_EVE_CERVED,FLG_PRES_RAPP,FLG_CRIME,DAT_INVI_LIST_PEP,DAT_INVI_LIST_TERR,DAT_INVI_LIST_CRIME,COD_STAT_ANMZ,DAT_VARZ_ANMZ,FLG_STATO_GIUR_ATTV,DAT_EVE_CERVED,FLG_EMIS_AZIO_PORT,COD_CATEG_PART,FLG_APPA_FINZ_PUBB,IMP_RISU_ECON,COD_NAZI_FIDU,COD_NAZI_TRUST,FLG_PRES_SOC_ANON,COD_NAZI_SOC_ANON,FLG_PRES_FNDZ,COD_NAZI_FNDZ,COD_PROF,FLG_POLI_ITA_LOCA,COD_POLI_ITA_LOCA,COD_AMB_PEP,COD_NAZA_SECO,COD_TAE,DES_INDI_SELE_INFOP,DES_CIVI_INDI_SELE_INFOP) VALUES (106828,'MARTINA VAGO ','09','PF ','VIALE AGRIGENTO SNC','74013 ',null,'TA','086',788802,'GINOSA','80459 ','80459 ',20230118,{ts '2023-01-18 10:35:49.724993'},null,' ',' ',' ','N','N','N',' ',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

-- Inserire il codice trovato nella query precedente nel where 

SELECT * FROM GAGT_RELUSNDG 
WHERE COD_USERID  IN ('T0R162','T0R164')

INSERT INTO GAGT_RELUSNDG (COD_USERID,COD_SOGGETTO,COD_ENTE_CENS,TMS_CENS,FLG_PRIN,COD_PROF_COND,COD_PROF_FIDI,COD_PROF_AUTO,COD_SOCRIFERIMENTO,TMS_VARZ,COD_ENTE_MODI,COD_TRX,COD_PROF_ANAG,COD_PROF_PEF,FLG_VISU_DIPN,COD_PROF_CONZ,COD_ORDI_PROF_AUTO,COD_CRUS_DEFL) VALUES ('T0R164  ',106828,'ELN     ',{ts '2023-09-04 11:18:49.216022'},'S','03   ','FD1  ','AUT1 ','09',{ts '2023-09-04 11:18:49.216022'},'ELN     ',null,'     ','     ','N','     ',1,null);

--- TABELE PEF 

SELECT * FROM GDET_PEF3STUT 
WHERE COD_UTEN='T0R162   ' 

--Qui invece si modifica solo il codice utente 

INSERT INTO GDET_PEF3STUT (COD_SOCRIFERIMENTO,COD_STAT_PRA,COD_UTEN,FLG_UTEN_ATT,COD_MODI_DERO_PEM,PRG_FACO_STAT_RISC,FLG_REVO,FLG_FORZ,FLG_RIPZ_GRUP,FLG_RIPZ) 

VALUES ('34','PROP','MLUIBT','S',null,1,'N','N','S','N') 

 
SELECT * FROM GDET_PEF3FACO
WHERE COD_USERID = 'T0R162  ' 

Stesso processo di prima 

-- tabella per condizioni kd 

SELECT * FROM GAGT_NDGPROAU
WHERE COD_SOGGETTO IN (25492,102718,111589)

--- TABELLA PER CANCELLARE
 SELECT * FROM ISIT_UIDPAMBI 


--sblocco conto NAQ
SELECT * FROM FFGT_LICREPAR
WHERE NUM_PR_LIN_CREDITO = 74854  --(linea di credito)
and cod_param_lin_sist in ( '280','180')

sintesi si vanno a mettere a N questi parametri 
SI sospende ticket e quando hanno finito li rimettiamo a s
 E POI SI CHIUDE QUANDO ARRIVA MAIL DI RIPRISTINO 


--richiesta scollegamento server
SELECT * FROM GDET_CTBSERWS  --scollegare
WHERE COD_SERVIZIO IN ('CEDACFIDI','CEDACREP')
 
--- PER SCOLLEGARE
 
UPDATE GDET_CTBSERWS
SET FLG_ATTIVO = 'N'
--SELECT * FROM GDET_CTBSERWS
WHERE FLG_ATTIVO = 'S'
AND COD_SERVIZIO IN ('CEDACFIDI','CEDACREP')
 
 
 
/*Ciao, server scollegato.
Attendiamo riscontro per ricollegare.
Marco
 
QUANDO ARRIVA MAIL CHIUDERE IL TICKET CON LA SEGUENTE NOTA:
Ciao, server collegato.
Marco*/
 
 
 
-- PER COLLEGARE
 
UPDATE GDET_CTBSERWS
SET FLG_ATTIVO = 'S'
--SELECT * FROM GDET_CTBSERWS
WHERE FLG_ATTIVO = 'N'
AND COD_SERVIZIO IN ('CEDACFIDI','CEDACREP')

--TK CRMPPZ19
--CREDEM PROD - CRMPPZ19 - Flusso situazione dei default Factor
--APRIRE TASSISTO02

