SELECT F.COD_NDG_CEDE AS CEDENTE,
SUBSTR(K.DES_RAGI_SOCL,1,44) AS RSOCCEDENTE,
COALESCE(K.COD_STAT_RISC,'') AS STCED,
COALESCE(K.COD_SETT_BAIT,0) AS SAE,
COALESCE(K.COD_RAMO_BAIT,0) AS RAE,
COALESCE(K.COD_ATEC,'') AS ATECO,
COALESCE(N.COD_SIGL_NAZI,'') AS NAZIONE,
COALESCE(K.COD_PROV_SELE,'') AS PROV_CEDE,
K.COD_ENTE_AZIE AS FILIALE,
CAST (SUBSTR(COALESCE(J.DES_RAGI_SOCL,''),1,44) AS CHAR(44) ) AS GESTORE,
COALESCE(J.COD_TIPO_SEGM_GEST,'') AS SEGM,
COALESCE(J.COD_TIPO_AREA_GEST,'') AS TEAM,
F.TURN AS TURNOVER,
F.INCA AS INCA,
F.SCNF AS SCNF,
F.CCES AS CONTO_CESSIONE,
F.EROG AS EROG,
F.ESPO AS ESPO,
COALESCE(M.MINTER,0) AS MINTER,
CASE WHEN F.DTASS <> 0 THEN
CAST(CAST(F.NATTI AS FLOAT) / CAST(F.DTASS AS FLOAT) AS DECIMAL(18,5) )
ELSE 0 END AS TASATT,
CASE WHEN F.DTASS <> 0 THEN
CAST(CAST(F.NPASS AS FLOAT) / CAST(F.DTASS AS FLOAT) AS DECIMAL(18,5) )
ELSE 0 END AS TASPAS,
F.SPRE AS SPREAD,
CASE WHEN F.TURN <> 0 AND F.COMM <> 0 THEN
CAST(CAST(F.COMM AS FLOAT) / CAST(F.TURN AS FLOAT) * 100 AS DECIMAL(18,5) )
ELSE 0 END AS PRCCOM,
CASE WHEN D.TDEB <> 0 AND D.DEBM <> 0 THEN
CAST(CAST(D.DEBM AS FLOAT) / CAST(D.TDEB AS FLOAT) * 100 AS DECIMAL(18,5) )
ELSE 0 END AS PRCDEBM,
100 - CASE WHEN D.TDEB <> 0 AND D.DEBM <> 0 THEN
CAST(CAST(D.DEBM AS FLOAT) / CAST(D.TDEB AS FLOAT) * 100 AS DECIMAL(18,5) )
ELSE 0 END AS PRCDEBNM,
CASE WHEN F.DRIPA <> 0 THEN
CAST(CAST(F.NRIPA AS FLOAT) / CAST(F.DRIPA AS FLOAT) AS DECIMAL(18) )
ELSE 0 END AS RITPAG,
CASE WHEN F.DRORG <> 0 THEN
CAST(CAST(F.NRORG AS FLOAT) / CAST(F.DRORG AS FLOAT) AS DECIMAL(18) )
ELSE 0 END AS ROTORI,
CASE WHEN F.DINCA <> 0 THEN
CAST(CAST(F.NINCA AS FLOAT) / CAST(F.DINCA AS FLOAT) AS DECIMAL(18) )
ELSE 0 END AS ROTINC,
CASE WHEN F.DREFF <> 0 THEN
CAST(CAST(F.NREFF AS FLOAT) / CAST(F.DREFF AS FLOAT) AS DECIMAL(18) )
ELSE 0 END AS ROTEFF
,SC.COD_NDC_LF AS COD_NDC_LF --NDC BANCA
,SC.COD_MDS AS COD_MDS --MODELLO DI SERVIZIO
,SC.DES_MDS AS DES_MDS --DESCRIZIONE MDS
,SC.COD_AREA_TER_SEG AS COD_AREA_TER_SEG --AREA TERRITORIALE
,SC.DES_AREA_TER_SEG AS DES_AREA_TER_SEG --DESCRIZIONE AREA
,SC.COD_DIR_TERR_SEG AS COD_DIR_TERR_SEG --DIREZIONE TERRITORIALE COMMERCIALE
,SC.DES_DIR_TERR_SEG AS DES_DIR_TERR_SEG --DESCRIZIONE DIR.TERR.
,SC.COD_FILIALE_SEG AS COD_FILIALE_SEG --FILIALE COMMERCIALE
,SC.DES_FILIALE_SEG AS DES_FILIALE_SEG --DESCRIZIONE FILIALE COMMERCIALE
,SC.COD_AREA_TER_ANAG AS COD_AREA_TER_ANAG --AREA SEGUIMENTO ANAGRAFICO
,SC.DES_AREA_TER_ANAG AS DES_AREA_TER_ANAG --DESCRIZIONE AREA ANAGRAFICA
,SC.COD_DIR_TER_ANAG AS COD_DIR_TER_ANAG --DIREZIONE TERRITORIALE ANAGRAFICA
,SC.DES_DIR_TER_ANAG AS DES_DIR_TER_ANAG --DESCRIZIONE DIR.ANAG.
,SC.COD_ANA_FIL_SEG AS COD_ANA_FIL_SEG --FILIALE ANAGRAFICA
,SC.DES_ANA_FIL_SEG AS DES_ANA_FIL_SEG --DESCRIZIONE FIL.ANAGRAFICA
FROM (
SELECT F.COD_SOCRIFERIMENTO,
F.COD_NDG_CEDE,
F.NUM_ANNO,
F.NUM_MESE,
SUM(F.IMP_TURN_PEND_PROG + F.IMP_TURN_PUTO_PROG) AS TURN,
SUM(F.IMP_SCAR_NFIN) AS SCNF,
SUM(F.IMP_INCA) AS INCA,
SUM(F.IMP_SALD_CONT) AS ESPO,
SUM(IMP_COMM_DEBI_PROG + IMP_COMM_HAND_PROG +
IMP_COMM_PEND_PROG + IMP_COMM_PUTO_PROG ) AS COMM,
SUM((IMP_MCRE_APTO_NOTF + IMP_MCRE_APTO_NNOT +
IMP_MCRE_NAPT_NOTF + IMP_MCRE_NAPT_NNOT ) -
(IMP_PAGT_SGAR + IMP_CDEB_MATY_APTO +
IMP_CDEB_MATY_NAPT)) AS CCES,
SUM(IMP_EROG_ACQU + IMP_EROG_ANTI +
IMP_EROG_SCON ) AS EROG,
SUM(F.IMP_DENM_RIPA_AC) AS DRIPA,
SUM(F.IMP_DENM_RORG_AC) AS DRORG,
SUM(F.IMP_DENM_INCA_AC) AS DINCA,
SUM(F.IMP_DENM_REFF_AC) AS DREFF,
SUM(F.IMP_NUMR_RIPA_AC) AS NRIPA,
SUM(F.IMP_NUMR_RORG_AC) AS NRORG,
SUM(F.IMP_NUMR_INCA_AC) AS NINCA,
SUM(F.IMP_NUMR_REFF_AC) AS NREFF,
SUM(F.IMP_NUMR_ATTI_CEDE) AS NATTI,
SUM(F.IMP_NUMR_PASS_CEDE) AS NPASS,
SUM(F.IMP_NUMD) AS DTASS,
CAST(AVG(F.PRC_SPRE) AS FLOAT) AS SPRE
FROM ccfp01.DWHT_FATTI F
WHERE F.COD_SOCRIFERIMENTO = '15'
AND F.NUM_ANNO = substr ('2023 - 12', 1, 4)
AND F.NUM_MESE = substr ('2023 - 12', 8, 2)
GROUP BY F.COD_SOCRIFERIMENTO,
F.COD_NDG_CEDE,
F.NUM_ANNO,   
F.NUM_MESE
) F 
INNER JOIN ccfp01.DWHT_SOGGETTO K ON
K.COD_SOCRIFERIMENTO = F.COD_SOCRIFERIMENTO
AND K.NUM_ANNO = F.NUM_ANNO
AND K.NUM_MESE = F.NUM_MESE
AND K.COD_SOGGETTO = F.COD_NDG_CEDE
LEFT OUTER JOIN (
SELECT F.COD_SOCRIFERIMENTO,
L.COD_NDG_CEDE,
F.NUM_ANNO,
F.NUM_MESE,
COUNT(F.COD_NDG_DEBI) AS TDEB,
SUM(CASE WHEN CAST (SUBSTR(cast((F.DAT_ULTI_CESS) as char(10)),1,4) AS INTEGER) = CAST(substr ('2023 - 12', 1, 4) AS INTEGER) AND
CAST (SUBSTR(cast((F.DAT_ULTI_CESS) as char(10)),6,2) AS INTEGER) = CAST(substr ('2023 - 12', 8, 2) AS INTEGER) THEN
1 ELSE 0 END ) AS DEBM
FROM ccfp01.DWHT_FIDOCPPA F
INNER JOIN ccfp01.DWHT_FIDOCEDE L ON
L.COD_SOCRIFERIMENTO = F.COD_SOCRIFERIMENTO
AND L.NUM_ANNO = F.NUM_ANNO
AND L.NUM_MESE = F.NUM_MESE
AND L.NUM_PR_LIN_CREDITO = F.NUM_PR_LIN_CREDITO
WHERE F.COD_SOCRIFERIMENTO = '15'
AND F.NUM_ANNO = substr ('2023 - 12', 1, 4)
AND F.NUM_MESE = substr ('2023 - 12', 8, 2)
AND F.COD_STATO_LIN_PLAF IN ('003','007','008')
GROUP BY F.COD_SOCRIFERIMENTO,
L.COD_NDG_CEDE,
F.NUM_ANNO,
F.NUM_MESE
) D ON
D.COD_SOCRIFERIMENTO = F.COD_SOCRIFERIMENTO
AND D.COD_NDG_CEDE = F.COD_NDG_CEDE
AND D.NUM_ANNO = F.NUM_ANNO
AND D.NUM_MESE = F.NUM_MESE
LEFT OUTER JOIN (
SELECT F.COD_SOCRIFERIMENTO,
F.COD_SOGGETTO AS COD_NDG_CEDE,
--RTRIM(CHAR(YEAR(F.DAT_RIFE))) AS NUM_ANNO,
RTRIM(SUBSTR(cast(F.DAT_RIFE as char(10)),1,4)) AS NUM_ANNO,
--RIGHT(DIGITS(MONTH(F.DAT_RIFE)),2) AS NUM_MESE,
SUBSTR(cast((F.DAT_RIFE) as char(10)),6,2) AS NUM_MESE,
SUM(F.IMP_IMPO) AS MINTER
FROM ccfp01.FDBT_DBIRETSC F
WHERE F.COD_SOCRIFERIMENTO = '15'
AND F.DAT_RIFE = (SELECT NUM_ANNO || '-' || NUM_MESE|| '-' || CAST(NUM_GIOR_MESE AS CHAR(2))
FROM ccfp01.DWHT_PERIODO
WHERE NUM_ANNO = substr ('2023 - 12', 1, 4)
AND NUM_MESE = substr ('2023 - 12', 8, 2))
GROUP BY F.COD_SOCRIFERIMENTO,
F.COD_SOGGETTO,
F.DAT_RIFE
) M ON
M.COD_SOCRIFERIMENTO = F.COD_SOCRIFERIMENTO
AND M.COD_NDG_CEDE = F.COD_NDG_CEDE
AND M.NUM_ANNO = F.NUM_ANNO
AND M.NUM_MESE = F.NUM_MESE
LEFT OUTER JOIN ccfp01.GDET_CTBNAZIO N ON
N.COD_NAZI = K.COD_NAZI_SELE
LEFT OUTER JOIN ccfp01.DWHT_SOGGGEST J ON
J.COD_SOCRIFERIMENTO = K.COD_SOCRIFERIMENTO
AND J.NUM_ANNO = K.NUM_ANNO
AND J.NUM_MESE = K.NUM_MESE  
AND J.COD_NDG_GEST = COALESCE(K.COD_NDG_GEST,0)
AND J.COD_TIPO_RELA = 'SGE'
LEFT OUTER JOIN ccfp01.GAGT_SEGMCOMM SC ON
SC.COD_SOCRIFERIMENTO = F.COD_SOCRIFERIMENTO
AND SC.COD_NDG_K4F = F.COD_NDG_CEDE
where ((K.COD_ENTE_AZIE = 'Tutte' or 'Tutte' = 'Tutte')
AND (J.COD_NDG_GEST = 999999 or 999999 = 999999)
AND (J.COD_TIPO_SEGM_GEST = 'Tutti' or 'Tutti' = 'Tutti')
AND (('Tutti' = 'Tutti' and 'Tutte' = 'Tutte')
or ('Tutti' <> 'Tutti' and ('Tutte' = 'Tutte' or J.COD_TIPO_AREA_GEST = 'Tutte'))))
ORDER BY CONTO_CESSIONE DESC