--FFGT_IDOCUMEN per funzione FI05


SELECT F.NUM_MESE, C.COD_TIPO_DATO, C.DES_TIPO_DATO, C.COD_TIPO_TOTA, C.DES_TIPO_TOTA, R.COD_PROG_STMP
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM01) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM01) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM01) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM01) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM01) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM01) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM01) END
END AS MM01
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM02) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM02) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM02) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM02) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM02) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM02) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM02) END
END AS MM02
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM03) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM03) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM03) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM03) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM03) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM03) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM03) END
END AS MM03
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM04) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM04) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM04) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM04) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM04) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM04) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM04) END
END AS MM04
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM05) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM05) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM05) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM05) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM05) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM05) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM05) END
END AS MM05
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM06) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM06) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM06) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM06) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM06) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM06) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM06) END
END AS MM06
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM07) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM07) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM07) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM07) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM07) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM07) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM07) END
END AS MM07
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM08) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM08) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM08) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM08) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM08) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM08) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM08) END
END AS MM08
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM09) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM09) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM09) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM09) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM09) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM09) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM09) END
END AS MM09
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM10) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM10) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM10) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM10) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM10) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM10) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM10) END
END AS MM10
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM11) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM11) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM11) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM11) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM11) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM11) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM11) END
END AS MM11
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM12) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM12) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM12) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM12) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM12) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM12) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM12) END
END AS MM12
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_MM13) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM13) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM13) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_MM13) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_MM13) AS FLOAT)) /
(CAST(SUM(IMP_DENM_MM13) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE SUM(IMP_MM13) END
END AS MM13
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_ROTA_AC) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_TOTA_ROTA_AC) AS FLOAT)) /
(CAST(SUM(IMP_DENM_ROTA_AC) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_ROTA_AC) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_TOTA_ROTA_AC) AS FLOAT)) /
(CAST(SUM(IMP_DENM_ROTA_AC) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'M'
THEN CAST(SUM(IMP_TOTA_ROTA_AC) / 12 AS DECIMAL (15,3))
ELSE SUM(IMP_TOTA_ROTA_AC) END
END
END AS TOTALE_MOBILE_AC
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_AC) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_TOTA_AC) AS FLOAT)) /
(CAST(SUM(IMP_DENM_AC) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_AC) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_TOTA_AC) AS FLOAT)) /
(CAST(SUM(IMP_DENM_AC) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'M'
THEN CAST(SUM(IMP_TOTA_AC) / CAST(F.NUM_MESE AS FLOAT) AS DECIMAL(15,3))
ELSE SUM(IMP_TOTA_AC) END END
END AS TOTALE_AC
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_ROTA_AP) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_TOTA_ROTA_AP) AS FLOAT)) /
(CAST(SUM(IMP_DENM_ROTA_AP) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_ROTA_AP) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_TOTA_ROTA_AP) AS FLOAT)) /
(CAST(SUM(IMP_DENM_ROTA_AP) AS FLOAT) * 100) AS DECIMAL (10,8)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'M'
THEN CAST(SUM(IMP_TOTA_ROTA_AP) / 12 AS DECIMAL (15,3))
ELSE SUM(IMP_TOTA_ROTA_AP) END
END
END AS TOTA_MOBILE_AP
,CASE WHEN C.COD_TIPO_TOTA = 'P'
THEN CASE WHEN SUM(IMP_DENM_AP) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_TOTA_AP) AS FLOAT)) /
(CAST(SUM(IMP_DENM_AP) AS FLOAT)) AS DECIMAL (15,6)) END
ELSE CASE WHEN C.COD_TIPO_TOTA = 'R'
THEN CASE WHEN SUM(IMP_DENM_AP) = 0
THEN 0 ELSE
CAST((CAST(SUM(IMP_TOTA_AP) AS FLOAT)) /
(CAST(SUM(IMP_ TA_AP) / CAST(F.NUM_MESE AS FLOAT) AS DECIMAL(15,3))
ELSE SUM(IMP_TOTA_AP) END END
END AS TOTALE_AP
FROM fpfp01.GDET_CTLDATRD C
JOIN fpfp01.GDET_RELDATRD R ON R.COD_SOCRIFERIMENTO = C.COD_SOCRIFERIMENTO
AND R.COD_TIPO_DATO = C.COD_TIPO_DATO
JOIN fpfp01.DWHT_FATTIRDI F ON F.COD_SOCRIFERIMENTO = R.COD_SOCRIFERIMENTO
AND F.COD_TIPO_REPO = R.COD_TIPO_REPO
AND F.COD_TIPO_DATO = R.COD_TIPO_DATO
JOIN fpfp01.GAGT_ENTEAZIE E ON F.COD_SOCRIFERIMENTO = E.COD_SOCRIFERIMENTO
AND F.COD_ENTE_AZIE = E.COD_ENTE_AZIE
WHERE F.COD_SOCRIFERIMENTO = '16'
and F.NUM_ANNO||' - '||F.NUM_MESE='2021 - 12'
AND F.COD_TIPO_REPO = 'MON'
AND C.COD_LING_USER = '086'
AND (F.COD_ENTE_AZIE = 'Tutte' or 'Tutte' = 'Tutte')
AND (F.COD_NDG_GEST = 999999 or '999999' = '999999')
AND (F.COD_TIPO_SEGM_GEST = 'Tutti' or 'Tutti' = 'Tutti')
AND (('Tutti' = 'Tutti' and 'Tutte' = 'Tutte') or ('Tutti' <> 'Tutti' and ('Tutte' = 'Tutte' or F.COD_TIPO_AREA_GEST = 'Tutte')))
AND (E.DES_AREA = 'Tutte' or 'Tutte' = 'Tutte')
GROUP BY F.NUM_MESE, C.COD_TIPO_DATO, C.DES_TIPO_DATO, C.COD_TIPO_TOTA, C.DES_TIPO_TOTA, R.COD_PROG_STMP
ORDER BY R.COD_PROG_STMP 

-----------------------------------------------------------


SELECT COD_NDG_CEDE AS CEDENTE,
CAST (
CASE WHEN K.COD_TIPO_SOGG = 'PF'
THEN RTRIM(K.DES_COGN) CONCAT ' ' CONCAT RTRIM(K.DES_NOME)
ELSE LEFT(K.DES_RAGI_SOCL,44)
END
AS CHAR(44)) AS RSOCCEDENTE,
COALESCE(K.COD_STAT_RISC,'') AS STCEDE,
COALESCE(K.COD_STAT_RISC_PREC,'') AS STCEDEP,
COALESCE(K.COD_SETT_BAIT,0) AS SAECEDE,
COALESCE(K.COD_RAMO_BAIT,0) AS RAECEDE,
COALESCE(K.COD_ATEC,'') AS ATECOCEDE,
COALESCE(N.COD_SIGL_NAZI,'') AS NAZCEDE,
COALESCE(KP.DES_REGO,'') AS REGOCEDE,
COALESCE(K.COD_PROV_SELE,'') AS PROVCEDE,
K.COD_ENTE_AZIE AS FILCEDE,
CAST (LEFT(COALESCE(J.DES_RAGI_SOCL,''),44) AS CHAR(44) ) AS GESTORE,
COALESCE(J.COD_TIPO_SEGM_GEST,'') AS SEGMCEDE,
COALESCE(J.COD_TIPO_AREA_GEST,'') AS TEAMCEDE,
K.IMP_FATT_DIVS_CONT AS FATTCEDE,
COD_NDG_DEBI AS DEBITORE,
CAST (
CASE WHEN W.COD_TIPO_SOGG = 'PF'
THEN RTRIM(W.DES_COGN) CONCAT ' ' CONCAT RTRIM(W.DES_NOME)
ELSE LEFT(W.DES_RAGI_SOCL,44)
END
AS CHAR(44)) AS RSOCDEBITORE,
COALESCE(W.COD_STAT_RISC,'') AS STDEBI,
COALESCE(W.COD_STAT_RISC_PREC,'') AS STDEBIP,
COALESCE(W.COD_SETT_BAIT,0) AS SAEDEBI,
COALESCE(W.COD_RAMO_BAIT,0) AS RAEDEBI,
COALESCE(W.COD_ATEC,'') AS ATECODEBI,
COALESCE(ND.COD_SIGL_NAZI,'') AS NAZDEBI,
COALESCE(WP.DES_REGO,'') AS REGODEBI,
COALESCE(W.COD_PROV_SELE,'') AS PROVDEBI,
W.COD_ENTE_AZIE AS FILDEBI,
CAST (LEFT(COALESCE(Y.DES_RAGI_SOCL,''),44) AS CHAR(44) ) AS RECUP,
COALESCE(Y.COD_TIPO_SEGM_GEST,'') AS SEGMDEBI,
COALESCE(Y.COD_TIPO_AREA_GEST,'') AS TEAMDEBI,
W.IMP_FATT_DIVS_CONT AS FATTDEBI,
NUM_PR_LIN_CRE_CED AS LCC,
L.COD_LINEA_SISTEMA AS LS,
D.DES_RID_LINEA_SIST AS DESCLS,
CASE WHEN L.FLG_UTO = 'N' THEN 'N'
ELSE
CASE WHEN L.COD_CLAU_MITI = '0' THEN 'E'
ELSE 'F'
END
END AS FLPUTO,
L.COD_MERC AS CODMERC,
D.FLG_CLAS_CRED AS CLCRED,
COALESCE(ER.COD_TIPO_ENTE, '') AS FONTSEGN,
X.COD_DIVS_FM AS DIVISA,
SUM(QTA_RATE_CRED_CEDU ) AS NFATANNO,
SUM(IMP_CNTV_PEND + IMP_CNTV_PUTO ) AS TOTANNO,
SUM(IMP_TURN_CRED_PEND + IMP_TURN_CRED_PUTO ) AS TOTANNO_DIVS,
SUM (CASE WHEN T.DAT_RIFE = '31.12.2021' THEN
QTA_RATE_CRED_CEDU
ELSE 0 END ) AS NFATMESE,
SUM (CASE WHEN T.DAT_RIFE = '31.12.2021' THEN
IMP_CNTV_PEND + IMP_CNTV_PUTO
ELSE 0 END ) AS TOTMESE,
SUM (CASE WHEN T.DAT_RIFE = '31.12.2021' THEN
IMP_TURN_CRED_PEND + IMP_TURN_CRED_PUTO
ELSE 0 END ) AS TOTMESE_DIVS
,SC.COD_NDC_LF AS COD_NDC_LF --NDC BANCA
,SC.COD_MDS AS COD_MDS --MODELLO DI SERVIZIO
,SC.DES_MDS AS DES_MDS --DESCRIZIONE MDS
,SC.COD_AREA_TER_SEG AS COD_AREA_TER_SEG --AREA TERRITORIALE
,SC.DES_AREA_TER_SEG AS DES_AREA_TER_SEG --DESCRIZIONE AREA
,SC.COD_DIR_TERR_SEG AS COD_DIR_TERR_SEG --DIREZIONE TERRITORIALE COMMERCIALE
,SC.DES_DIR_TERR_SEG AS DES_DIR_TERR_SEG --DESCRIZIONE DIR.TERR.
,SC.COD_FILIALE_SEG AS COD_FILIALE_SEG --FILIALE COMMERCIALE
,SC.DES_FILIALE_SEG AS DES_FILIALE_SEG --DESCRIZIONE FILIALE COMMERCIALE
,SC.COD_AREA_TER_ANAG AS COD_AREA_TER_ANAG --AREA SEGUIMENTO ANAGRAFICO
,SC.DES_AREA_TER_ANAG AS DES_AREA_TER_ANAG --DESCRIZIONE AREA ANAGRAFICA
,SC.COD_DIR_TER_ANAG AS COD_DIR_TER_ANAG --DIREZIONE TERRITORIALE ANAGRAFICA
,SC.DES_DIR_TER_ANAG AS DES_DIR_TER_ANAG --DESCRIZIONE DIR.ANAG.
,SC.COD_ANA_FIL_SEG AS COD_ANA_FIL_SEG --FILIALE ANAGRAFICA
,SC.DES_ANA_FIL_SEG AS DES_ANA_FIL_SEG --DESCRIZIONE FIL.ANAGRAFICA
FROM fpfp01.FDBT_DBITODEB T
INNER JOIN fpfp01.FDBT_DBIFIDI L ON
T.COD_SOCRIFERIMENTO = L.COD_SOCRIFERIMENTO
AND T.DAT_RIFE = L.DAT_RIFE
AND T.NUM_PR_LIN_CRE_CED = L.NUM_PR_LIN_CREDITO
INNER JOIN fpfp01.GDET_CTBLSIST D ON
L.COD_SOCRIFERIMENTO = D.COD_SOCRIFERIMENTO
AND L.COD_LINEA_SISTEMA = D.COD_LINEA_SISTEMA
INNER JOIN fpfp01.FDBT_DBIANAG K ON
K.COD_SOCRIFERIMENTO = T.COD_SOCRIFERIMENTO
AND K.DAT_RIFE = '31.12.2021'
AND K.COD_SOGGETTO = T.COD_NDG_CEDE
LEFT JOIN fpfp01.GDET_CTLPROVI KP ON
KP.COD_PROV = K.COD_PROV_SELE
AND KP.COD_LING_USER = '086'
INNER JOIN fpfp01.FDBT_DBIANAG W ON
W.COD_SOCRIFERIMENTO = T.COD_SOCRIFERIMENTO
AND W.DAT_RIFE = '31.12.2021'
AND W.COD_SOGGETTO = T.COD_NDG_DEBI
LEFT JOIN fpfp01.GDET_CTLPROVI WP ON
WP.COD_PROV = W.COD_PROV_SELE
AND WP.COD_LING_USER = '086'
LEFT OUTER JOIN fpfp01.GDET_CTBNAZIO N ON
N.COD_NAZI = K.COD_NAZI_SELE
LEFT OUTER JOIN fpfp01.GDET_CTBNAZIO ND ON
ND.COD_NAZI = W.COD_NAZI_SELE
LEFT OUTER JOIN fpfp01.GDET_CTBDIVIS X ON
X.COD_DIVS = T.COD_DIVS
LEFT OUTER JOIN fpfp01.DWHT_SOGGGEST J ON
J.COD_SOCRIFERIMENTO = K.COD_SOCRIFERIMENTO
AND J.NUM_ANNO = RTRIM(CHAR(YEAR(K.DAT_RIFE)))
AND J.NUM_MESE = RIGHT(DIGITS(MONTH(K.DAT_RIFE)),2)
AND J.COD_NDG_GEST = COALESCE(K.COD_ENTE_GEST,0)
AND J.COD_TIPO_RELA = 'SGE'
LEFT OUTER JOIN fpfp01.DWHT_SOGGGEST Y ON
Y.COD_SOCRIFERIMENTO = W.COD_SOCRIFERIMENTO
AND Y.NUM_ANNO = RTRIM(CHAR(YEAR(W.DAT_RIFE)))
AND Y.NUM_MESE = RIGHT(DIGITS(MONTH(W.DAT_RIFE)),2)
AND Y.COD_NDG_GEST = COALESCE(W.COD_ENTE_RECU_DEBI,0)
AND Y.COD_TIPO_RELA = 'SRD'
LEFT OUTER JOIN fpfp01.GAGT_ENTIRIST ER ON
ER.COD_SOCRIFERIMENTO = T.COD_SOCRIFERIMENTO
AND ER.COD_NDG_SOGG = T.COD_NDG_CEDE
AND ER.COD_TIPO_SOGG = 'C'
AND ER.DAT_INIZ <= '31.12.2021'
AND COALESCE(ER.DAT_FINE, '9999-12-31') > '31.12.2021'
LEFT OUTER JOIN fpfp01.GAGT_SEGMCOMM SC ON
SC.COD_SOCRIFERIMENTO = T.COD_SOCRIFERIMENTO
AND SC.COD_NDG_K4F = T.COD_NDG_CEDE
WHERE T.COD_SOCRIFERIMENTO = '16'
AND YEAR(T.DAT_RIFE) = YEAR('31.12.2021')
AND T.DAT_RIFE <= '31.12.2021'
GROUP BY NUM_PR_LIN_CRE_CED,
COD_NDG_CEDE,
K.DES_RAGI_SOCL,
K.COD_STAT_RISC,
K.COD_SETT_BAIT,
K.COD_RAMO_BAIT,
N.COD_SIGL_NAZI,
KP.DES_REGO,
K.COD_PROV_SELE,
K.COD_STAT_RISC_PREC,
W.COD_STAT_RISC_PREC,
COD_NDG_DEBI,
W.DES_RAGI_SOCL,
W.COD_STAT_RISC,
W.COD_SETT_BAIT,
W.COD_RAMO_BAIT,
ND.COD_SIGL_NAZI,
WP.DES_REGO,
W.COD_PROV_SELE,
T.COD_DIVS,
L.COD_LINEA_SISTEMA,
D.DES_RID_LINEA_SIST,
D.FLG_CLAS_CRED,
X.COD_DIVS_FM,
K.COD_ATEC,
L.FLG_UTO,
L.COD_MERC,
L.COD_CLAU_MITI,
K.COD_TIPO_SOGG,
K.DES_COGN,
K.DES_NOME,
K.COD_ENTE_AZIE,
J.DES_RAGI_SOCL,
J.COD_TIPO_SEGM_GEST,
J.COD_TIPO_AREA_GEST,
W.COD_TIPO_SOGG,
W.DES_COGN,
W.DES_NOME,
W.COD_ENTE_AZIE,
W.COD_ATEC,
Y.DES_RAGI_SOCL,
Y.COD_TIPO_SEGM_GEST,
Y.COD_TIPO_AREA_GEST,
K.IMP_FATT_DIVS_CONT,
W.IMP_FATT_DIVS_CONT,
ER.COD_TIPO_ENTE,
SC.COD_NDC_LF,
SC.COD_MDS,
SC.DES_MDS,
SC.COD_AREA_TER_SEG,
SC.DES_AREA_TER_SEG,
SC.COD_DIR_TERR_SEG,
SC.DES_DIR_TERR_SEG,
SC.COD_FILIALE_SEG,
SC.DES_FILIALE_SEG,
SC.COD_AREA_TER_ANAG,
SC.DES_AREA_TER_ANAG,
SC.COD_DIR_TER_ANAG,
SC.DES_DIR_TER_ANAG,
SC.COD_ANA_FIL_SEG,
SC.DES_ANA_FIL_SEG
ORDER BY 1,29,15
WITH UR


--2024/36   incongruenza base dati
controllare su k4f_error sul db e sulla relasogg 

SELECT * FROM K4F_ERROR
ORDER BY TMS_CENS DESC

SELECT * FROM GAGT_RELASOGG
WHERE COD_SOGGETTO ='2013195'

select * from GAGT_RELASOGG
where COD_SOGG_RELA = 2013195

SELECT * FROM gdet_ctltrela
where cod_tipo_rela ='ECO'

--poi controllare sul k4f su an08 e vedere il gruppo economico


--2024/38 - IFIR -
AND COD_SOCRIFERIMENTO = '16'
 
SELECT * FROM FFGT_CONTO --SALD DISP -8783,89
WHERE NUM_PR_LIN_CREDITO = 10384
AND COD_SOCRIFERIMENTO = '16'
 
SELECT SUM(IMP_MOVI_FINZ) FROM FOPT_MOVICONT --8783,89
WHERE NUM_PR_LIN_CREDITO = 10384
AND DAT_DISP_CEDE IS NOT NULL
AND COD_SOCRIFERIMENTO = '16'
 
SELECT SUM(IMP_MOVI_FINZ) FROM FOPT_MONTECRE
WHERE NUM_PR_LIN_CREDITO = 10384 -- -1085,75
AND COD_SOCRIFERIMENTO  = '16'
 
SELECT COD_CAUS, SUM(IMP_MCRE) FROM FOPT_MONTECRE
WHERE NUM_PR_LIN_CREDITO = 10384
GROUP BY COD_CAUS

SELECT * FROM fopt_movicont
WHERE COD_CAUS = 'C30D'


--pef in collaudo TEST SPPI
SET CURRENT SQLID ='FPFC01'


SELECT * FROM FFGT_PRATDIGI
WHERE COD_SOCRIFERIMENTO = '16'
AND NUM_PR_PRAT_DIGI ='1065941'
--AND FLG_SPPI_TEST

SELECT * FROM FFGT_LCCSTAGE
WHERE NUM_PR_LIN_CREDITO ='13142'

SELECT * FROM ffgt_lcrdebi
WHERE NUM_PR_LIN_CREDITO ='13142'