SET CURRENT SQLID = 'IGFP01' --settare ambiente fucino

--start g
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC 
LIKE '%IGGPSP01%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--fine g
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%IGGPSP02%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--VERIFICARE CHE SIANO ARRIVATE LE MAIL DEI 5 FLUSSI DA CEDACRI (INTORNO ALLE 8) !!ATTENZIONE A VOLTE VANNO NELLA POSTA INDESIDERATA.

--FLUSSI VS CEDACRI (IF94 A VOLTE è VUOTO)
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('IGGPIF4R','IGGPIF19','IGGPIF94','IGGPAG82','IGGPAR53','IGGPIF93')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC


SELECT * FROM SCPR_LOGPROC -- VERIFICA CHE NON CI SIANO KEYFLXML IN 9
WHERE COD_PROC LIKE '%LQ%'
AND COD_OUTP LIKE '%KEYFLXML%'
AND FLG_STAT <> '2'
ORDER BY TMS_CENS DESC --ASC nel caso si richiede il crescente

SELECT * FROM TCON_DLVQUEUE --VERIFICA CHE NON CI SIANO FLUSSI BONIFICI IN ERRORE
ORDER BY TMS_CENS DESC
 
--IGGPIF54 - Flusso giornaliero VM verso CEDACRI
SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('OBJFING')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC


--CONTROLLARE CHE SIANO OK
SELECT * FROM SCPR_ELABTIME
WHERE COD_PROC IN ('IGGPIF54','IGGPIF64','IGMPIF54','IGMPIF64','IGMPIF55','IGMPIF65')
ORDER BY DAT_ELAB DESC

--SCARTI
SELECT * FROM FCGT_MOVIECBC
WHERE COD_STAT_MOVI = 'S'

--VERIFICA GENERICA ERRORI
SELECT * FROM SCPR_ELABTIME
WHERE DES_ESITO LIKE '%ERROR%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--VERIFICA GENERICA OUTPUT IN ERRORE
select * from scpr_logproc 
where (flg_stat in ('3') or (flg_stat ='1' and cod_outp<>'WEB'))   
and date(tms_cens) >= '2023-06-01'
order by num_id desc 

--2024/29
--estrazione con mappatura prodotto cedacri Pxx e prodotti K4F con relativa descrizione
SELECT A.COD_ORIG, B.DES_EST_LINEA_SIST, A.COD_DEST FROM GDET_DECODK4F A, GDET_CTBLSIST B
WHERE A.COD_ORIG = B.COD_LINEA_SISTEMA
AND A.COD_TIPO_DECF = 'LSTDS'
AND B.COD_LINEA_SISTEMA IN (211,'241','242','431','441','561','741','742','744','745')

-2024/31
--update sul filiale da 001 a 83 (cod_ente_azie)
MTA3MjA2

--2024/8
--estrazione di ndg codice esterno cedacri
select * from gagt_codieste -- tabella per codice cedacri

--2024/19
--estrazione per ndg e mettere in stato uno poi lo portano in stato 3
SELECT * FROM FOPT_GEDOCCRE 
WHERE COD_NDG_CEDE = 1000807
COD_sTAT_DOCU -> PORTARE IN STATO 001

--2024/34 soggetto da eliminare quindi da fare update con stato 010(estinto)
update gagt_ndgutent
set cod_stato ='010'
where cod_soggetto='1000852'

INSERT INTO GAGT_SPORBANC 
("COD_SPOR","DES_SPOR","COD_SOGGETTO","COD_ABI","COD_CAB","COD_TELEFONO","DES_SIGLA","COD_CAB_COMU","COD_PROV_SPOR","DES_COMU_SPOR","DES_INDI_SPOR","COD_CAP_SPOR","COD_NAZI","DAT_FINE_VALI","COD_SWIFT","COD_ENTE_MODI","COD_ENTE_CENS","DAT_CENS","TIM_STAT","COD_ABI_PREC","COD_CAB_PREC","COD_CIN_ABI","COD_CIN_CAB","COD_ABI_AUI","COD_NAZI_AUI","FLG_BONI_URGE","DES_RID_SPOR") 
VALUES ('0869254040 ','BANCA DI CREDITO COOPERATIVO DI BRESCIA S.C. FILIALE DI BAGNOLO MELLA',null,8692,54040,null,null,540401,'BS','BAGNOLO MELLA','VIA GRAMSCI 129 - B','25021 ','086',null,null,'HD','HD',20231010,{ts '2024-02-05 11:11:01.832154'},null,null,'6','1',null,null,'N',null);
20231207000681588                


--2024/39 - BANCA DEL FUCINO
SELECT * FROM FOPT_GEDOCCRE
WHERE COD_SOCRIFERIMENTO = '24'
AND COD_NDG_CEDE = 1000679
AND COD_NDG_DEBI = 1000681

--bisogna andare su questa tabella entrando con cedente e debitore che indicano 
--e mettere il COD_STAT_DOCU in stato 002
-- aspettare cliente 

--gestione parametro ffgt_lisipara
--se flg delibara è S bisogna modificare da pef
-- ffgt_valparls (valori) ticket 2024/40 fucino


--ticker 2024/65
SELECT a.cod_sogg_codi, a.cod_estr, b.des_sogg_uten  FROM gagt_codieste a , gagt_ndg b
where a.cod_sogg_codi = b.cod_soggetto
and cod_tipo_codi=100





SELECT * FROM FDBT_DBINUMSC  --tabella per trovaro descrizone tasso ER08

WHERE NUM_PR_LIN_CREDITO = 1700





SELECT * FROM FOPT_PARTITA
WHERE NUM_PR_LIN_CREDITO = 10384
AND DAT_CHIU_DEBI_FCTG IS NULL
AND COD_SOCRIFERIMENTO = '16'
 
SELECT * FROM FFGT_CONTO --SALD DISP -8783,89
WHERE NUM_PR_LIN_CREDITO = 10384
AND COD_SOCRIFERIMENTO = '16'
 
SELECT SUM(IMP_MOVI_FINZ) FROM FOPT_MOVICONT --8783,89
WHERE NUM_PR_LIN_CREDITO = 10384
AND DAT_DISP_CEDE IS NOT NULL
AND COD_SOCRIFERIMENTO = '16'
 
SELECT SUM(IMP_MOVI_FINZ) FROM FOPT_MONTECRE
WHERE NUM_PR_LIN_CREDITO = 10384 -- -1085,75
AND COD_SOCRIFERIMENTO  = '16'
 
SELECT COD_CAUS, SUM(IMP_MCRE) FROM FOPT_MONTECRE
WHERE NUM_PR_LIN_CREDITO = 10384
GROUP BY COD_CAUS