SET CURRENT SQLID ='CCFP01'

SELECT ORDINALE, CASE ORDINALE 
WHEN 'A' THEN 'Numero dei cedenti attivi per TO' 
WHEN 'B' THEN 'Numerosita dei cedenti' 
WHEN 'C' THEN 'Numerosita dei ceduti'
END AS DES_RIGA, COUNT(*) AS NROREC
FROM 
(SELECT DISTINCT 'A' AS ORDINALE, COD_NDG_CEDE AS SOGG FROM DWHT_FATTI A
WHERE A.COD_SOCRIFERIMENTO = '15' 
AND ( (A.NUM_ANNO = (SELECT SUBSTR(CHAR(DAT_CONT,ISO),1,4) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15') 
       AND A.NUM_MESE <= (SELECT SUBSTR(CHAR(DAT_CONT,ISO),6,2) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' ) ) 
   OR (A.NUM_ANNO = (SELECT (SUBSTR(CHAR(DAT_CONT - 1 YEAR,ISO),1,4)) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' AND NOT MONTH(DAT_CONT) = 12) 
	   AND A.NUM_MESE > (SELECT SUBSTR(CHAR(DAT_CONT,ISO),6,2) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' ) ) )
AND (A.IMP_TURN_PEND_PROG > 0 OR A.IMP_TURN_PUTO_PROG > 0) 
UNION
SELECT DISTINCT 'B' AS ORDINALE, COD_NDG_CEDE AS SOGG FROM DWHT_FATTI A
WHERE A.COD_SOCRIFERIMENTO = '15' 
AND ( (A.NUM_ANNO = (SELECT SUBSTR(CHAR(DAT_CONT,ISO),1,4) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15') 
       AND A.NUM_MESE <= (SELECT SUBSTR(CHAR(DAT_CONT,ISO),6,2) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' ) ) 
   OR (A.NUM_ANNO = (SELECT (SUBSTR(CHAR(DAT_CONT - 1 YEAR,ISO),1,4)) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' AND NOT MONTH(DAT_CONT) = 12) 
	   AND A.NUM_MESE > (SELECT SUBSTR(CHAR(DAT_CONT,ISO),6,2) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' ) ) )
AND ( ((A.IMP_MCRE_NAPT_NOTF + A.IMP_MCRE_NAPT_NNOT) > 0 OR (A.IMP_MCRE_APTO_NOTF + A.IMP_MCRE_APTO_NNOT) > 0)
  OR   (A.IMP_TURN_PEND_PROG > 0 OR A.IMP_TURN_PUTO_PROG > 0) ) 
UNION
SELECT DISTINCT 'C' AS ORDINALE, COD_NDG_DEBI AS SOGG FROM DWHT_FATTI A
WHERE A.COD_SOCRIFERIMENTO = '15' 
AND ( (A.NUM_ANNO = (SELECT SUBSTR(CHAR(DAT_CONT,ISO),1,4) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15') 
       AND A.NUM_MESE <= (SELECT SUBSTR(CHAR(DAT_CONT,ISO),6,2) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' ) ) 
   OR (A.NUM_ANNO = (SELECT (SUBSTR(CHAR(DAT_CONT - 1 YEAR,ISO),1,4)) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' AND NOT MONTH(DAT_CONT) = 12) 
	   AND A.NUM_MESE > (SELECT SUBSTR(CHAR(DAT_CONT,ISO),6,2) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' ) ) )
AND ( (A.IMP_MCRE_NAPT_NOTF + A.IMP_MCRE_NAPT_NNOT) > 0 OR (A.IMP_MCRE_APTO_NOTF + A.IMP_MCRE_APTO_NNOT) > 0)
) AS A
GROUP BY ORDINALE
WITH UR

--- estrazione per 3006 debitori 
SELECT DISTINCT COD_NDG_DEBI FROM DWHT_FATTI A -- DISTINCT ELIMINA I DOPPIONI 
WHERE COD_SOCRIFERIMENTO = '15' 
AND ( (NUM_ANNO = (SELECT SUBSTR(CHAR(DAT_CONT,ISO),1,4) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15') --ANNO 2023
       AND NUM_MESE <= (SELECT SUBSTR(CHAR(DAT_CONT,ISO),6,2) FROM TCON_DATCONT --> 2023 <= 12
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' ) ) -- MESI 12 
   OR (NUM_ANNO = (SELECT (SUBSTR(CHAR(DAT_CONT - 1 YEAR,ISO),1,4)) FROM TCON_DATCONT 
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' AND NOT MONTH(DAT_CONT) = 12) --2022
	   AND NUM_MESE > (SELECT SUBSTR(CHAR(DAT_CONT,ISO),6,2) FROM TCON_DATCONT -- 2022 > 12
                     WHERE FLAG_TIPO_ELAB = 'M' AND COD_SOCRIFERIMENTO = '15' ) ) )
AND ( (IMP_MCRE_NAPT_NOTF + IMP_MCRE_NAPT_NNOT) > 0 OR (IMP_MCRE_APTO_NOTF + IMP_MCRE_APTO_NNOT) > 0)
AND NUM_ANNO ='2023'
GROUP BY COD_NDG_DEBI /* ultime due righe non sicuro*/



--cod tipo boll data contabile cedente linea debitore importo
-- sia per cedente e per debitore A (cendente) B(debitore) GANGT_NDG Fopt_fatboll --AMBIENTE ICS CSFP01(PROD)

-- contabili emesse


--- query bcc 
SELECT A.COD_TIPO_BOLL,A.DAT_CONT,A.COD_NDG_CEDE,B.DES_SOGG_UTEN,A.COD_NDG_DEBI,C.DES_SOGG_UTEN,A.IMP_FACC 
FROM FOPT_FATBOLL A
LEFT JOIN GAGT_NDG B
ON A.COD_NDG_CEDE = B.COD_SOGGETTO 
LEFT JOIN GAGT_NDG C
ON A.COD_NDG_DEBI = C.COD_SOGGETTO
WHERE A.DAT_CONT BETWEEN '2023-01-01' AND '2023-12-31'



--query per multi soc (ifir)
SELECT * FROM TCON_DMCQUEUE --> tabella tcoverto in cui si vedono gli output/flussi inviati via pec e non
WHERE COD_SOCRIFERIMENTO = '16'
ORDER BY TMS_CENS DESC
 
SELECT * FROM FOPT_PARTITA -- query per le fatture
WHERE COD_SOCRIFERIMENTO = '16'
ORDER BY DAT_REGI DESC
 
SELECT * FROM FOPT_DESTBONI -- query per i bonifici
WHERE COD_SOCRIFERIMENTO = '16'
ORDER BY TMS_CENS DESC
 
SELECT * FROM FOPT_RAGGRUPP -- query per le cessione 
WHERE COD_SOCRIFERIMENTO = '16'
ORDER BY TMS_CENS DESC
 
SELECT * FROM SCPR_LOGPROC --query per i log 
WHERE COD_SOCRIFERIMENTO = '16' 
ORDER BY TMS_CENS DESC

--2024/27
--via denominazione , indirizzo della banca, poi fare insert con i dati messi nella mail del ticket abi e car uniti sul cod_spor