--per ticket di reset password intervenire solo se utenza bloccata 
--per ticket CENTRALE RISCHI girare a vigilanza "2024/53" 
--ticket in "Richiesta di valutazione --> accettare --> in valutazione" come ticket 2024/63 (BCC)
--tabelle autorizzazione pef gdet_peffaco
SET CURRENT SQLID ='CCFP01'

SELECT
  round(SUM(COALESCE(IMP_NUMD_PROG,0)))  as "NUMERI_DARE"   ,
round(SUM(COALESCE(IMP_NUMA_PROG,0))) as "NUMERI_AVERE"
              ,round(SUM(COALESCE(IMP_NUMD_DILZ_PROG,0))) as
"NUMERI_DILAZIONE_DARE" ,round(SUM(COALESCE(IMP_NUMA_DILZ_PROG,0)))as
"NUMERI_DILAZIONE_AVERE"
              ,round(SUM(COALESCE(IMP_NUMD_RITA_PROG,0)))
"NUMERI_RITARDATO_DARE" ,round(SUM(COALESCE(IMP_NUMA_RITA_PROG,0))) as
"NUMERI_RITARDATO_AVERE"
FROM DWHT_FATTI    A
WHERE A.COD_SOCRIFERIMENTO = '15'
AND A.NUM_ANNO ='2023'
AND A.NUM_MESE = '12'
--gagt_ndgutent tabella per gli ndgutent 
--gagt_soggperg tabella per i soggetti
SELECT * FROM SCPR_LOGPROC
WHERE NUM_ID='(NUMERO ID)'

SELECT a.cod_stato,a.cod_soggetto, b.des_ragi_socl, b.cod_piva,b.cod_fisc FROM gagt_ndgutent a, gagt_soggperg b 
WHERE a.cod_soggetto = b.cod_soggetto 
AND a.cod_stato >='002'  -- estrazione stato soggetto ragione sociale Piva cf per bcc e poi esportazione in excel


  

SELECT DISTINCT(a.cod_soggetto),b.des_ragi_socl,a.cod_stato,C.DES_STAT_SOGG, b.cod_piva,b.cod_fisc FROM gagt_ndgutent a, gagt_soggperg b, GDET_CTLSTSOG c 
WHERE a.cod_soggetto = b.cod_soggetto 
and c.cod_stat_sogg = a.COD_STATO
AND C.COD_LING_USER ='086' -- estrazione con aggiunta descrizione stato anagrafica

-- per simulazione mensile utiliazzare K4F_SERVIZIO se N (spento) s(normale) ctrl+h (sostituisce valore)

--per le commissioni tralasciare p70
--per debitore sempre inte la tabella da prendere
--da tsfoglio staffa cedente tabulato riepologativo per staffa debitore scarti per errori

--reporting --> cambi ip da link siti--> commerciali--> analisi portofoglio--> dettaglio cedenti--> export in excel 


ctbstdso -- tabella standard 98 livello di giro conto
verspart --storico di partita
GDET_ctblsist -- linea sistema
joi 
ctbpatar --tabella parametri
licrepar --liste dei parametri
lineacq -- linea d'acquisto

--ticket 2024/45
SELECT * FROM GDET_CTBPARAM
WHERE COD_PARAM_LIN_SIST = 280
 
SELECT * FROM FFGT_LINEACRE
WHERE NUM_PR_LIN_CREDITO IN (108111, 109976)
 
SELECT * FROM FFGT_LISIPARA
WHERE COD_LINEA_SISTEMA IN (742)
AND COD_PARAM_LIN_SIST = '280'
 
SELECT * FROM FFGT_VALPARLS
WHERE COD_PARAM_LIN_SIST = 280
AND COD_LINEA_SISTEMA = 742
 
SELECT * FROM FFGT_STOLCPAR
WHERE NUM_PR_LIN_CREDITO IN (108111, 109976)
AND COD_PARAM_LIN_SIST = 280
 
SELECT * FROM FFGT_LINEACQU
WHERE NUM_LINE_CRED_ACQU IN (108111, 109976)

UPDATE DWHT_FATTI
SET IMP_ALTR_COMM = 0
WHERE COD_SOCRIFERIMENTO = '15'
AND   NUM_ANNO = '2023' AND NUM_MESE='12'
AND  IMP_ALTR_COMM <> 0
AND  IMP_COMM_CEDE_MENS = 0

--2024/45
--update su parametri di coppia su tabella ffgt_licreparm(linea di credito)
--gdet_ctbparam -> descrizioni dei parametri
--ffgt_lisipara -> come sono gestiti i parametri sulle varie linee di sistema
--(esempio O - obbligatorio ,  N - non gestito ecc...)

--per revoca mandato SDD
SELECT * FROM FOPT_RIDBANCA --Valorizzo la DAT_FINE_OPER e il COD_STAT_AUTO_RID a 004
WHERE COD_RIFE_RID = '0107366000000001'

UPDATE FOPT_RIDBANCA
SET COD_STAT_AUTO_RID= '004',  DAT_FINE_OPER = '2024-04-04'
WHERE COD_RIFE_RID = '0017447000000001'

--2024/29--
-- utente non riceve pec per le sue utenze controllare con query sottostante
select * from even_evtqueue -- tabella eventi mail wof bcc prod
order by tms_cens desc


--2024/54
SELECT A.NUM_PR_LIN_CREDITO, A.COD_CAUS, B.DES_CAUS_ESTE, A.IMP_MOVI_FINZ, A.DAT_CONT, A.DAT_VALU_CEDE FROM FOPT_MOVICONT A,GDET_CTBCAUPA B 
WHERE A.COD_CAUS = B.COD_CAUS
AND NUM_PR_LIN_CREDITO = 868
AND DAT_DISP_CEDE IS NOT NULL
--legame con tabella movicont e ctbcaupa(causali) per estrarre tabella per il ticket bcc 2024/54

--2024/56
-- iban errati notificare al cliente l'errore controllare su K4F AN06

TCON_DMCqueue

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','GP14FT01','DOCXML ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.476308'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','GP14ST03','FNOTIF ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.512072'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT01','DOCXML ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.548502'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES('14','MP14FT67','DOCXML ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.584009'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT91','DOCXML ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.617438'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14ST20','FESCOXML','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.651206'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14ST23','FESCOXML','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.686923'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14ST27','FESCOXML','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.720392'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14FT45','FESCOXML','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.754210'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14FG80','XMLREVO ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.788223'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14FG80','XMLREVO ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.826918'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','GP14FT01','DOCXML ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.864181'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','GP14ST03','FNOTIF ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.906735'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14FG80','XMLSTP ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.943820'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14FG80','XMLSTP ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:26.977183'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT01','DOCXML ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.011445'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT67','DOCXML ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.050681'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT91','DOCXML ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.086124'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14ST20','FESCOXML','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.120736'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14ST23','FESCOXML','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.157700'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14ST27','FESCOXML','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.191008'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14FT45','FESCOXML','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.230366'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT45','DOCXML ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.264423'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT45','DOCXML ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.305414'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT76','DOCXML ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.341718'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','MP14FT76','DOCXML ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.376047'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','SP14ST30','FISOLXML','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.409494'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','SP14ST30','FISOLXML','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.443182'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14KN37','XMLSTP ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.478660'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES('14','RP14KN37','XMLSTP ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.515710'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14KN38','XMLSTP ','CARTACEAMASSIVA ','CARTACEAMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','N','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.548970'});

INSERT INTO TCON_DMCSOGG (COD_SOCRIFERIMENTO,COD_PROC,COD_OUTP,IDCANALE,TIPOCANALE,COD_SOGG,TMS_CENS,ATTRIBUTE_KEY,FLG_ATTIVA,COD_TRX,COD_USERID,COD_TRX_VARZ,COD_USERID_VARZ,TMS_CENS_VARZ) VALUES ('14','RP14KN38','XMLSTP ','PECMASSIVA ','PECMASSIVA_DEFAULT ','1140799 ',{d '2024-02-06'},' ','S','HD ','HD ','HD ','HD ',{ts '2024-02-06 11:27:27.583849'});



--2024/56
--errore iban segnalare al cliente l'errore

--2024/66
--PREL_PRATICA tabella pratiche
SELECT
COD_SOCRIFERIMENTO
,NUM_ANNO          
,NUM_MESE          
,COD_SOGGETTO      
,COD_CR_SOGGETTO    
,COD_SOGG_COLL      
,COD_CR_SOGG_COLL  
,COD_SOGG_COLL_ORIG
,FLG_AZIE_SIST
,count(*)
FROM  ccfp01.DWHT_LEGAMICR
where COD_SOGGETTO = 63168
group by COD_SOCRIFERIMENTO
,NUM_ANNO          
,NUM_MESE          
,COD_SOGGETTO      
,COD_CR_SOGGETTO    
,COD_SOGG_COLL      
,COD_CR_SOGG_COLL  
,COD_SOGG_COLL_ORIG
,FLG_AZIE_SIST
having count(*) > 1

--2024/73 --inserimento per codice ragione sociale 
SELECT * FROM GDET_RELSGSET
WHERE COD_SPEC_GIUR = 'SCP'
 
INSERT INTO GDET_RELSGSET (COD_SOCRIFERIMENTO,COD_SPEC_GIUR,COD_SETT_BAIT) VALUES ('01','SCP  ',430);


--2024/74 per questo tipo di ticket censire utente in k4f e legare con una insert
INSERT INTO GAGT_RELUSNDG (COD_USERID,COD_SOGGETTO,COD_ENTE_CENS,TMS_CENS,FLG_PRIN,COD_PROF_COND,COD_PROF_FIDI,COD_PROF_AUTO,COD_SOCRIFERIMENTO,TMS_VARZ,COD_ENTE_MODI,COD_TRX,COD_PROF_ANAG,COD_PROF_PEF,FLG_VISU_DIPN,COD_PROF_CONZ,COD_ORDI_PROF_AUTO,COD_CRUS_DEFL)
 VALUES ('VITALI',112202,'QMF',{ts '2015-10-02 10:52:19.916109'},'S','CD0  ','FD1  ','AUTC ','15',{ts '2015-10-02 10:52:19.916109'},'QMF     ','QMF  ','     ','     ','N','     ',1,null);


 --2024/77 ticket su estrazione fatture 2023 codice c411
 -- metterle su excel
SELECT B.COD_SOGGETTO, B.DES_SOGG_UTEN,C.NUM_PR_LIN_CREDITO,A.COD_CAUS, A.IMP_RIGA, A.DAT_INIZ_CPTZ FROM FOPT_RIGAPART A , GAGT_NDG B, FFGT_LINEACRE C
WHERE B.COD_SOGGETTO = C.COD_SOGGETTO
AND A.NUM_PR_LIN_CREDITO = C.NUM_PR_LIN_CREDITO
AND  COD_CAUS ='C411'
AND DAT_INIZ_CPTZ BETWEEN '2023-01-01' AND '2023-12-31'
ORDER BY TMS_CENS ASC


--2024/78 estrazione gruppi per codice soggetto e codice soggetto relazione 
SELECT A.COD_SOGGETTO,B.DES_SOGG_UTEN,A.COD_SOGG_RELA, C.DES_SOGG_UTEN, A.COD_TIPO_PART,A.COD_TIPO_RELA ,A.DAT_INIZ,A.DAT_FINE FROM GAGT_RELASOGG A, GAGT_NDG B, GAGT_NDG C
WHERE A.COD_SOGGETTO = B.COD_SOGGETTO
AND A.COD_SOGG_RELA = C.COD_SOGGETTO
AND A.COD_TIPO_RELA ='ECO'
AND A.COD_SOCRIFERIMENTO ='15'
ORDER BY COD_SOGGETTO DESC

SELECT * FROM GAGT_SPORBANC

--ticket 2024/88 

SELECT F.COD_SOCRIFERIMENTO,
F.COD_NDG_CEDE,
F.NUM_ANNO,
F.NUM_MESE,
SUM(F.IMP_TURN_PEND_PROG + F.IMP_TURN_PUTO_PROG) AS TURN,
SUM(F.IMP_SCAR_NFIN) AS SCNF,
SUM(F.IMP_INCA) AS INCA,
SUM(F.IMP_SALD_CONT) AS ESPO,
SUM(IMP_COMM_DEBI_PROG + IMP_COMM_HAND_PROG +
IMP_COMM_PEND_PROG + IMP_COMM_PUTO_PROG ) AS COMM,
SUM((IMP_MCRE_APTO_NOTF + IMP_MCRE_APTO_NNOT +
IMP_MCRE_NAPT_NOTF + IMP_MCRE_NAPT_NNOT ) -
(IMP_PAGT_SGAR + IMP_CDEB_MATY_APTO +
IMP_CDEB_MATY_NAPT)) AS CCES,
SUM(IMP_EROG_ACQU + IMP_EROG_ANTI 
IMP_EROG_SCON ) AS EROG,
SUM(F.IMP_DENM_RIPA_AC) AS DRIPA,
SUM(F.IMP_DENM_RORG_AC) AS DRORG,
SUM(F.IMP_DENM_INCA_AC) AS DINCA,
SUM(F.IMP_DENM_REFF_AC) AS DREFF,
SUM(F.IMP_NUMR_RIPA_AC) AS NRIPA,
SUM(F.IMP_NUMR_RORG_AC) AS NRORG,
SUM(F.IMP_NUMR_INCA_AC) AS NINCA,
SUM(F.IMP_NUMR_REFF_AC) AS NREFF,
SUM(F.IMP_NUMR_ATTI_CEDE) AS NATTI,
SUM(F.IMP_NUMR_PASS_CEDE) AS NPASS,
SUM(F.IMP_NUMD) AS DTASS,
CAST(AVG(F.PRC_SPRE) AS FLOAT) AS SPRE
FROM DWHT_FATTI F
WHERE F.COD_NDG_CEDE ='19977'
AND F.NUM_MESE='12'
AND F.NUM_ANNO ='2023'
GROUP BY  F.COD_SOCRIFERIMENTO,
F.COD_NDG_CEDE,
F.NUM_ANNO,
F.NUM_MESE


SELECT * FROM DWHT_FATTI ----SUM(IMP_SALD_CONT)
WHERE COD_NDG_CEDE ='19977'
AND NUM_MESE='12'
AND NUM_ANNO ='2023'
AND NUM_PR_LIN_CREDITO ='104832'

--------------------------------------------------------------------


-- ticket 2024/93 assegnare 23 filiale per cedenti
SELECT * FROM GDET_ctbtrela
where cod_socriferimento ='15'

SELECT * FROM gagt_relusndg
where cod_userid ='DIFEO'

UPDATE "CCFP01"."GAGT_NDGUTENT" SET "COD_ENTE_AZIE"='23' 
where cod_soggetto in ('15426','112236','112237','112238','112239','112240','112241','82325','21121','112242','112243','112244','112245','112246','112247','112248','112249','66632','112250','112251','112252','77284','112253','112254','112255','112256','112110','112257','112258','112259','112260','112261','112262','112263','112264','112265','112266','112267','112268','112269','81388','112270','112271','112272','112273','112274','112275','112276','112277','112278','112279','112280','112281','112282','112283','112284','112285','75822','112286','112287','112288','112289','112290','112291','112292','112293','112294','112295','112296','112297','80570','87361','112298','112299','112300','109744','20887','112301','91976','112302','112303','81389','9560','112304','112305','107067','112306','112307','112308','112309','112310','81386','112311','112312','112313','112314','112315','112316','112317','112318','112319','112320','112321','112322')

--2024/97 
--mettere NDG --> cod_alfa_stan
SELECT * FROM GDET_CTBSTDSO
WHERE COD_TIPO_STAN='988'


insert prel_profgrpu (comporre insert cod utent creato)
insert prel_facodeli 
INSERT INTO GAGT_RELUSNDG (COD_USERID,COD_SOGGETTO,COD_ENTE_CENS,TMS_CENS,FLG_PRIN,COD_PROF_COND,COD_PROF_FIDI,COD_PROF_AUTO,COD_SOCRIFERIMENTO,TMS_VARZ,COD_ENTE_MODI,COD_TRX,COD_PROF_ANAG,COD_PROF_PEF,FLG_VISU_DIPN,COD_PROF_CONZ,COD_ORDI_PROF_AUTO,COD_CRUS_DEFL)
 VALUES ('VITALI',112202,'QMF',{ts '2015-10-02 10:52:19.916109'},'S','CD0  ','FD1  ','AUTC ','15',{ts '2015-10-02 10:52:19.916109'},'QMF     ','QMF  ','     ','     ','N','     ',1,null);

INSERT INTO "CCFP01"."ISIT_UTENTI" ("COD_UTEN","DES_UTEN","COD_GRUP_UTEN","DES_PSW","DAT_INIZ_PSW","DAT_SCAD_PSW","DAT_MODI_PSW","NUM_TENT_EFFR","COD_CENT_COST","THH_INIZ_COLL","THH_FINE_COLL","TIM_STAT","COD_UTENMODI","DES_NOTE","COD_GRUT_COND","COD_GRUT_FIDI","COD_TIPO_INSE","FLG_CONNESSO","COD_PROF_COND","COD_PROF_FIDI","COD_PROF_AUTO","FLG_VISU_TMNL_FLUA","COD_USER_SSO","FLG_ATVZ_SSO","FLG_ESCL_SSO_LEV2","COD_LNGE_USER","DES_PSW_WEB","TMS_INIZ_PSW_WEB","TMS_SCAD_PSW_WEB","TMS_MODI_PSW_WEB","DES_USER_AGEN_STRI","COD_EMUL_TYPE","FLG_USER_ADMN","DES_MAIL","COD_USER_SSO_EXT") VALUES ('CELEST              ','Donatella Celestini','K4FG','',null,null,null,0,'99        ',null,null,{ts '2018-04-24 12:03:01.858020'},'SECUADMIN','','          ','          ','  ','N','CD0  ','FD1  ','AUTI ','N','CELESTIN            ','N',' ','      ','CFyF96+7TvsrWGjc+PtnZARpPp0=',{ts '2018-05-07 09:22:24.357857'},{ts '2024-03-15 16:59:03.571950'},{ts '2024-02-14 16:59:03.571950'},'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0','NOEMUL    ','N','','');

maildocprod da girare a studio informatica assistenza@smouse.it

GesCR da girare ad Aronica collega di vigilanza

--BCC Factoring S.p.A. - Cessione CEDENTE DA WOF CCFP01 ; ERRORE
SELECT * FROM EVEN_EVTQUEUE
WHERE DATE(TMS_CENS) >= '2024-02-28'
AND COD_STATO = 'FAILED'
 
SELECT * FROM EVEN_PKGREMOT
WHERE ID_PACKAGE = 11814

--Inseriti cambi in AOF BCC UBAE
 --andare su banca d'italia e vedere il valore valuta

INSERT INTO fopt_cambio VALUES ('001','XXX',{d '2024-02-29'},1.0826,'HD',current_timestamp,'CAMB','HD',current_timestamp,'242');
INSERT INTO fopt_cambio VALUES ('002','XXX',{d '2024-02-29'},0.85655,'HD',current_timestamp,'CAMB','HD',current_timestamp,'242');

 
(questo solo per BCC) INSERT INTO fopt_cambio VALUES ('003','XXX',{d '2024-02-29'},0.9534,'HD',current_timestamp,'CAMB','HD',current_timestamp,'242');


--2024/110
SELECT * FROM FFGT_LINEMODI
WHERE NUM_PR_LIN_CREDITO = 109971
--seccata ultima riga 


select * from fart_antiricl


--ticket 2024/134
SELECT * FROM prel_pratica

WHERE COD_PRAT = 77694
 
SELECT * FROM PREL_WLOGFLUS

WHERE COD_PRAT = '77694'

ORDER BY PRG_PASS DESC
 
SELECT * FROM SCPR_SKPARAM
WHERE DES_SKPR LIKE '%77694%'

SELECT COD_SOCRIFERIMENTO,NUM_ANNO,NUM_MESE,COD_SOGGETTO,COD_CR_SOGGETTO,COD_SOGG_COLL,COD_CR_SOGG_COLL,COD_SOGG_COLL_ORIG,FLG_AZIE_SIST,count(*)
FROM  ccfp01.DWHT_LEGAMICR
where COD_SOGGETTO = 60243
group by COD_SOCRIFERIMENTO,NUM_ANNO,NUM_MESE,COD_SOGGETTO,COD_CR_SOGGETTO,COD_SOGG_COLL,COD_CR_SOGG_COLL,COD_SOGG_COLL_ORIG,FLG_AZIE_SIST
having count(*) > 1

--TICKET 2024/136 ERRORE APERTURA PEF 
SELECT * FROM K4F_ERROR
ORDER BY TMS_CENS DESC --> Controllare il campo DES_OPERAZIONE = 030

SELECT * FROM FFGT_RICHFIDO
WHERE COD_SOGGETTO ='64106'

-- aprire grimaldel
--vedere la MOVE 30
   EXEC SQL
      SELECT  A.FLG_PRAT_MP_CEDE
              ,A.FLG_PRAT_MP_DEBI
              ,A.FLG_SVIN_DELI_EST
         INTO :RICHFIDO.FLG-PRAT-MP-CEDE
             ,:RICHFIDO.FLG-PRAT-MP-DEBI
             ,:RICHFIDO.FLG-SVIN-DELI-EST
         FROM  FFGT_RICHFIDO A
              ,PREL_PRATICA  B
        WHERE  A.COD_SOCRIFERIMENTO = :SH-LNK-COD-SOCI-RIFE
          AND  A.NUM_PR_RICHIE_FIDO = :RICHFIDO.NUM-PR-RICHIE-FIDO
          AND  A.COD_SOCRIFERIMENTO = B.COD_SOCRIFERIMENTO
          AND  A.NUM_PR_RICHIE_FIDO = B.COD_PRAT
     END-EXEC
     MOVE SQLCODE TO SEA-SQLCODE.
     IF NOT SEA-SQL-RETURN-NORMAL
        MOVE 30    

--aumento linea del cedente CONSORZIO STABILE  80052
INSERT INTO FFGT_PROLCPAR (COD_SOCRIFERIMENTO,NUM_PR_LIN_CREDITO,COD_PARAM_LIN_SIST,PRG_VALO,COD_VALO_PARA,IMP_VALO_PARA,PRC_VALO_PARA,DAT_VALO_PARA,NUM_VALO_PARA,COD_ENTE_MODI,COD_ENTE_CENS,DAT_CENS,TIM_STAT,COD_TRSZ)
 VALUES ('15',55989,'328',1,null,null,null,null,null,'HD    ','HD    ',20231108,{ts '2024-03-06 16:53:26.132542'},'HD  ');
va inserito il parametro che hanno indicato (328) su PROLCPAR


SELECT concat(concat(SUBSTR(cast(dat_cont as char(10)),1,4),' - '),SUBSTR(cast(dat_cont as char(10)),6,2)) as DATA_AGG,
concat(concat(SUBSTR(cast(dat_cont as char(10)),1,4),' - '),SUBSTR(cast(dat_cont as char(10)),6,2)) as ANNOMESE_CONT,
dat_cont as DAT_CONT
FROM igfp01.TCON_DATCONT
WHERE FLAG_TIPO_ELAB ='M' 

--2024/34 estrazione partite e tipo partite per cedente e debitore
select  a.COD_NDG_DEBI_FCTG, b.ANA_SOGGETTORID,  a.cod_ndg_Cede, c.ANA_SOGGETTORID, a.cod_prtt, a.COD_TIPO_PRTT,d.DES_TIPO_PRTT, A.DAT_REGI, a.DAT_EMIS, a.DAT_SCAD_EMIT,a.imp_facc
from FOPT_PARTITA a, gagt_ndgutent b, gagt_ndgutent c, GDET_CTBTIPAR d
where   b.cod_soggetto = a.COD_NDG_DEBI_FCTG
and   c.cod_soggetto = a.cod_ndg_Cede
and a.COD_TIPO_PRTT = d.COD_TIPO_PRTT
and dat_REGI BETWEEN '2024-04-01' AND '2024-04-30'
order by a.dat_emis desc



--estrazione per cedenti e debitori attivi per la pec 
SELECT DISTINCT A.COD_SOGGETTO, A.NUM_PR_LIN_CREDITO, A.FLG_OPRN, B.DES_INDI_MAIL, B.NUM_INDI_SOGG, B.DAT_INIZ_VALI, B.DAT_FINE_VALI, B.FLG_PEC  FROM FFGT_LINEACRE A, GAGT_MAILSOGG B
WHERE A.COD_STATO_LIN_PLAF NOT IN ('004','010')
AND A.COD_SOGGETTO = B.COD_SOGGETTO
AND EXISTS (SELECT NUM_PR_LIN_CREDITO FROM FOPT_MOVICONT
WHERE DAT_CONT >= '2023-05-01')
 
SELECT DISTINCT A.cod_ndg_debi, A.NUM_PR_LIN_CREDITO, A.FLG_OPRN, B.DES_INDI_MAIL, B.NUM_INDI_SOGG, B.DAT_INIZ_VALI, B.DAT_FINE_VALI, B.FLG_PEC  FROM FFGT_FIDOCOPP A, GAGT_MAILSOGG B
WHERE A.COD_STAT_LIN_PLAF NOT IN ('004','010')
AND A.COD_NDG_DEBI = B.COD_SOGGETTO
AND EXISTS (SELECT NUM_PR_LIN_CREDITO FROM FOPT_MOVICONT
WHERE DAT_CONT >= '2023-05-01')

--estrazione debitori attualmente attivi collegati al cedente e al gestore di riferimento 
SELECT  C.COD_NDG_DEBI, D.ANA_SOGGETTORID,C.COD_STAT_LIN_PLAF,B.COD_SOGGETTO, A.COD_SOGGETTO, E.ANA_SOGGETTORID ,a.COD_STATO_LIN_PLAF , B1.COD_SOGGETTO  
FROM FFGT_LINEACRE A, GAGT_RELASOGG B, GAGT_RELASOGG B1, ffgt_fidocopp c,GAGT_NDGUTENT D, GAGT_NDGUTENT E
WHERE A.NUM_PR_LIN_CREDITO = C.NUM_PR_LIN_CREDITO
AND C.COD_NDG_DEBI = D.COD_SOGGETTO
AND C.COD_NDG_DEBI = B.COD_SOGG_RELA
AND A.COD_SOGGETTO = B1.COD_SOGG_RELA
AND A.COD_SOGGETTO = E.COD_SOGGETTO
AND B.COD_TIPO_RELA = 'SGE' 
AND B1.COD_TIPO_RELA = 'SGE'
AND A.COD_STATO_LIN_PLAF NOT IN ('004','010')
AND C.COD_STAT_LIN_PLAF NOT IN ('004','010')
AND B.DAT_FINE IS NULL
AND B1.DAT_FINE IS NULL

--estrazione riassiucurazione cedente debitore richiesta 2024/289
SELECT A.COD_NDG_CEDE, B.DES_SOGG_UTEN, A.COD_NDG_DEBI_FCTG, C.DES_SOGG_UTEN, A.NUM_PR_LIN_CREDITO, A.DAT_EMIS,A.DAT_REGI, d.COD_LINEA_SISTEMA, A.COD_TIPO_PRTT, G.DES_TIPO_PRTT, A.COD_PRTT_XXXL, a.IMP_FACC, A.DAT_CHIU_DEBI_FCTG,
E.COD_NDG_RIAS, F.DES_SOGG_UTEN, E.COD_POLI_RIAS, E.IMP_APPR_RIAS
FROM FOPT_PARTITA A, GAGT_NDG B, GAGT_NDG C , FFGT_LINEACRE D, FFGT_RELNDGRI E, GAGT_NDG F, GDET_CTBTIPAR G
WHERE A.DAT_EMIS >= '2024-02-01'
AND A.DAT_REGI >= '2024-04-01' 
AND B.COD_SOGGETTO = A.COD_NDG_CEDE
AND C.COD_SOGGETTO = A.COD_NDG_DEBI_FCTG
and a.NUM_PR_LIN_CREDITO = d.NUM_PR_LIN_CREDITO
AND A.COD_NDG_DEBI_FCTG = E.COD_SOGGETTO
AND F.COD_SOGGETTO = E.COD_NDG_RIAS
AND A.COD_TIPO_PRTT <> 'P00'
AND A.COD_TIPO_PRTT = G.COD_TIPO_PRTT

--estrazione rapporti chiusi
SELECT A.NUM_PR_LIN_CREDITO,A.COD_SOGGETTO,B.ANA_SOGGETTORID,A.DAT_REVO,DATE(A.TIM_STAT) AS DATA_ARCHIVIAZIONE,A.COD_STATO_LIN_PLAF
FROM FFGT_LINEACRE A, GAGT_NDGUTENT B 
WHERE A.COD_SOGGETTO = B.COD_SOGGETTO
AND A.COD_STATO_LIN_PLAF IN ('008', '010')
AND A.DAT_REVO BETWEEN '2023-01-01' AND '2023-12-31'
AND NOT EXISTS (SELECT * FROM FFGT_LINEACRE C
  			   WHERE C.COD_SOGGETTO = A.COD_SOGGETTO
  			   AND C.COD_STATO_LIN_PLAF NOT IN ('008', '010')
  			   )

