SET CURRENT SQLID = 'BUFP01'

SELECT * FROM k4f_servizio

--- inizio giornaliera 

SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%BUGPSP01%'
ORDER BY DAT_ELAB DESC, TIM_START DESC


--- fine giornaliera 

SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%BUGPSP02%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

select * from scpr_logproc 
where (flg_stat in ('3') or (flg_stat ='1' and cod_outp<>'WEB'))   
and date(tms_cens) = '2024-09-16'
order by num_id desc

-- fluddi verso cedacri giornaliero


SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP
FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('BUGPIF19','BUGPIF15','BUGPIF20','BUGPAR53','BUGPIF56','BUGPIF62','BUGPIF92','OBJFING')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC



SELECT * FROM  SCPR_LOGPROC
WHERE COD_PROC IN ('BUGPIF54','BUGPIF64')
ORDER BY TMS_CENS DESC

SELECT * FROM FCGT_MOVIECBC
WHERE COD_STAT_MOVI = 'S'

-- NON FARE PIU 

select * from BUFP01.FRFT_TRACCERF
where cod_socriferimento = '18'
and cod_rife not in ('DWX011', 'DWX070', 'DWX027', 'BANCSOGG', 'DETMOVCO', 'MOVPARTI', 'SCADENRF', 'INTRPRTT')



SELECT * FROM SCPR_ELABTIME
where (COD_PROC like '%DW72%' or COD_PROC like '%DW70%')
order by DAT_ELAB desc , tim_start desc


SELECT * FROM SCPR_ELABTIME
where (COD_PROC like '%DW11%' or COD_PROC like '%DW17%'or COD_PROC like '%DW27%')
order by DAT_ELAB desc , tim_start desc

---- flussi giornalieri la data deve avere lo stesso giorno del bollettino 

SELECT * FROM SCPR_ELABTIME
WHERE COD_PROC LIKE '%AG83%'
ORDER BY DAT_ELAB DESC

SELECT * FROM SCPR_ELABTIME
WHERE COD_PROC LIKE '%AG84%'
ORDER BY DAT_ELAB DESC

SELECT * FROM SCPR_ELABTIME
WHERE COD_PROC LIKE '%IN20%'
ORDER BY DAT_ELAB DESC

SELECT * FROM SCPR_ELABTIME
WHERE COD_PROC LIKE '%IN21%'
ORDER BY DAT_ELAB DESC

SELECT * FROM SCPR_ELABTIME
WHERE COD_PROC LIKE '%KN72%'
ORDER BY DAT_ELAB DESC

---non fae piu 
SELECT * FROM SCPR_ELABTIME
WHERE COD_PROC LIKE '%KN73%'
ORDER BY DAT_ELAB DESC


--Data inizio mensile:
SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%BUMPSP01%'
ORDER BY DAT_ELAB DESC, TIM_START DESC

--Data fine mensile:

SELECT COD_PROC, DAT_ELAB, TIM_END  FROM SCPR_ELABTIME
WHERE COD_PROC  LIKE '%BUMPSP02%'
ORDER BY DAT_ELAB DESC, TIM_START DESC


-- FLUSSO MENSILE VALUE MANAGER VERSO CEDACRI

SELECT P.NUM_ID, P.COD_PROC, P.FLG_STAT, P.DES_FILE, D.TMS_CENS, D.TMS_SEND, D.DLV_STATUS, P.COD_OUTP FROM SCPR_LOGPROC P, TCON_DLVQUEUE D
WHERE P.COD_PROC IN ('OBJFINM')
AND P.NUM_ID = D.NUM_ID
ORDER BY P.TMS_CENS DESC


SELECT * FROM  SCPR_LOGPROC
WHERE COD_PROC IN ('BUMPIF54','BUMPIF64')
ORDER BY TMS_CENS DESC




SELECT * FROM SCPR_ELABTIME
WHERE DES_ESITO = 'ERROR'
ORDER BY DAT_ELAB DESC, TIM_START DESC
